### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [67]:
# Dependencies and Setup
import pandas as pd

# File to Load 
file_to_load = "C:/Users/kyran/Desktop/Pandas-Challenge/HeroesOfPymoli/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

In [68]:
# Checking data
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [69]:
#Checking data types
purchase_data.dtypes

Purchase ID      int64
SN              object
Age              int64
Gender          object
Item ID          int64
Item Name       object
Price          float64
dtype: object

In [37]:
purchase_data.describe()

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   92.114103    3.050987
std     225.310896    6.659444   52.775943    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   48.000000    1.980000
50%     389.500000   22.000000   93.000000    3.150000
75%     584.250000   25.000000  139.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

In [38]:
purchase_data_groupby = purchase_data.groupby(by= ['SN', 'Age', 'Gender'])
purchase_data_groupby

In [39]:
for name, dataframe in purchase_data_groupby:
    print(name)
    print(dataframe)

('Adairialis76', 16, 'Male')
     Purchase ID            SN  Age Gender  Item ID          Item Name  Price
467          467  Adairialis76   16   Male      123  Twilight's Carver   2.28
('Adastirin33', 35, 'Female')
     Purchase ID           SN  Age  Gender  Item ID  \
142          142  Adastirin33   35  Female      175

                      Item Name  Price
142  Woeful Adamantite Claymore   4.48
('Aeda94', 17, 'Male')
     Purchase ID      SN  Age Gender  Item ID                      Item Name  \
388          388  Aeda94   17   Male      128  Blazeguard, Reach of Eternity

     Price
388   4.91
('Aela59', 21, 'Male')
    Purchase ID      SN  Age Gender  Item ID  \
28           28  Aela59   21   Male      119

                                    Item Name  Price
28  Stormbringer, Dark Blade of Ending Misery   4.32
('Aelaria33', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
630          630  Aelaria33   23   Male      171   Scalpel   1.79
('Aelastirin39', 23, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
218          218  Aelastirin39   23   Male       76
766          766  Aelastirin39   23   Male       58

                             Item Name  Price
218           Haunted Bronzed Bludgeon   3.15
766  Freak's Bite, Favor of Holy Might   4.14
('Aelidru27', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID            Item Name  Price
705          705  Aelidru27   22   Male      183  Dragon's Greatsword   1.09
('Aelin32', 20, 'Male')
     Purchase ID       SN  Age Gender  Item ID                   Item Name  \
52            52  Aelin32   20   Male       60                        Wolf
87            87  Aelin32   20   Male      151                   Severance
584          584  Aelin32   20   Male      115  Spectral Diamond Doomblade

     Price
52    3.54
87    3.40
584   2.04
('Aelly27', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID                Item Name  Price
43            43  Aelly27   24   Male      116  Renewed Skeletal Katana   4.18
428          428  Aelly27   24   Male       14           Possessed Core   2.61
('Aellynun67', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID        Item Name  Price
286          286  Aellynun67   25   Male      153  Mercenary Sabre   3.74
('Aellyria80', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
746          746  Aellyria80   23   Male      159

                             Item Name  Price
746  Oathbreaker, Spellblade of Trials   3.08
('Aelollo59', 33, 'Male')
     Purchase ID         SN  Age Gender  Item ID           Item Name  Price
203          203  Aelollo59   33   Male        3        Phantomlight   2.49
431          431  Aelollo59   33   Male      172  Blade of the Grave   3.14
('Aenarap34', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID             Item Name  Price
183          183  Aenarap34   21   Male       15  Soul Infused Crystal   2.96
('Aeral43', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID                   Item Name  \
263          263  Aeral43   24   Male       78  Glimmer, Ender of the Moon

     Price
263    4.4
('Aeral68', 43, 'Male')
     Purchase ID       SN  Age Gender  Item ID                   Item Name  \
674          674  Aeral68   43   Male       77  Piety, Guardian of Riddles

     Price
674    4.0
('Aeral97', 23, 'Male')
     Purchase ID       SN  Age Gender  Item ID                Item Name  Price
167          167  Aeral97   23   Male      157  Spada, Etcher of Hatred    4.8
('Aeralria27', 10, 'Male')
    Purchase ID          SN  Age Gender  Item ID         Item Name  Price
32           32  Aeralria27   10   Male      133  Faith's Scimitar   4.09
('Aeralstical35', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID  \
583          583  Aeralstical35   20   Male       49

                            Item Name  Price
583  The Oculus, Token of Lost Worlds   2.96
('Aeri84', 24, 'Male')
     Purchase ID      SN  Age Gender  Item ID Item Name  Price
303          303  Aeri84   24   Male       71    Demise   1.61
('Aerillorin70', 16, 'Male')
     Purchase ID            SN  Age Gender  Item ID   Item Name  Price
381          381  Aerillorin70   16   Male       83  Lifebender   3.33
('Aerithllora36', 29, 'Female')
     Purchase ID             SN  Age  Gender  Item ID        Item Name  Price
274          274  Aerithllora36   29  Female       82          Nirvana   4.90
578          578  Aerithllora36   29  Female      153  Mercenary Sabre   3.74
('Aerithnucal56', 15, 'Male')
     Purchase ID             SN  Age Gender  Item ID     Item Name  Price
324          324  Aerithnucal56   15   Male      154  Feral Katana    4.4
('Aerithnuphos61', 39, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
517          517  Aerithnuphos61   39   Male      128

                         Item Name  Price
517  Blazeguard, Reach of Eternity   4.91
('Aerithriaphos45', 20, 'Male')
    Purchase ID               SN  Age Gender  Item ID          Item Name  \
40           40  Aerithriaphos45   20   Male      143  Frenzied Scimitar

    Price
40   1.56
('Aerithriaphos46', 16, 'Male')
     Purchase ID               SN  Age Gender  Item ID  \
236          236  Aerithriaphos46   16   Male      107

                     Item Name  Price
236  Splitter, Foe Of Subtlety   2.18
('Aesri53', 31, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
541          541  Aesri53   31   Male      161    Devine   1.76
('Aesty53', 21, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
124          124  Aesty53   21   Male      150
253          253  Aesty53   21   Male       28

                            Item Name  Price
124                         Deathraze   2.85
253  Flux, Destroyer of Due Diligence   1.06
('Aestysu37', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID    Item Name  Price
309          309  Aestysu37   25   Male      170  Shadowsteel   3.97
416          416  Aestysu37   25   Male       13     Serenity   1.41
('Aesur96', 23, 'Male')
     Purchase ID       SN  Age Gender  Item ID    Item Name  Price
468          468  Aesur96   23   Male       30  Stormcaller   2.21
('Aesurstilis64', 25, 'Male')
     Purchase ID             SN  Age Gender  Item ID   Item Name  Price
405          405  Aesurstilis64   25   Male       70  Hope's End   1.03
('Aethedru70', 21, 'Female')
     Purchase ID          SN  Age  Gender  Item ID Item Name  Price
775          775  Aethedru70   21  Female       60      Wolf   3.54
('Aidai53', 19, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
219          219  Aidai53   19   Male       57

                           Item Name  Price
219  Despair, Favor of Due Diligence    4.6
('Aidai61', 21, 'Male')
     Purchase ID       SN  Age Gender  Item ID                  Item Name  \
282          282  Aidai61   21   Male      155  War-Forged Gold Deflector

     Price
282   1.01
('Aidai73', 19, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
720          720  Aidai73   19   Male      159

                             Item Name  Price
720  Oathbreaker, Spellblade of Trials   3.08
('Aidaillodeu39', 18, 'Male')
     Purchase ID             SN  Age Gender  Item ID         Item Name  Price
42            42  Aidaillodeu39   18   Male       72     Winter's Bite   3.77
146          146  Aidaillodeu39   18   Male      133  Faith's Scimitar   4.09
('Aidain51', 39, 'Female')
     Purchase ID        SN  Age  Gender  Item ID                 Item Name  \
516          516  Aidain51   39  Female       35  Heartless Bone Dualblade

     Price
516   3.45
('Aidaira26', 30, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
730          730  Aidaira26   30   Male      178

                                        Item Name  Price
730  Oathbreaker, Last Hope of the Breaking Storm   4.23
('Aiduecal76', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID        Item Name  Price
97            97  Aiduecal76   20   Male      134  Undead Crusader   4.50
670          670  Aiduecal76   20   Male      120           Agatha   3.08
('Aiduesu86', 22, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
429          429  Aiduesu86   22  Female      179

                           Item Name  Price
429  Wolf, Promise of the Moonwalker   4.48
('Aillyriadru65', 24, 'Male')
     Purchase ID             SN  Age Gender  Item ID  Item Name  Price
523          523  Aillyriadru65   24   Male       21  Souleater    1.1
('Aillyrin83', 10, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
155          155  Aillyrin83   10  Female       98

                       Item Name  Price
155  Deadline, Voice Of Subtlety   2.89
('Aina42', 25, 'Male')
     Purchase ID      SN  Age Gender  Item ID            Item Name  Price
83            83  Aina42   25   Male       12                Dawne   1.02
363          363  Aina42   25   Male       45  Glinting Glass Edge   3.85
373          373  Aina42   25   Male      103       Singed Scalpel   4.35
('Aina43', 19, 'Male')
    Purchase ID      SN  Age Gender  Item ID                    Item Name  \
94           94  Aina43   19   Male       96  Blood-Forged Skeletal Spine

    Price
94   3.09
('Airi27', 24, 'Other / Non-Disclosed')
     Purchase ID      SN  Age                 Gender  Item ID  \
637          637  Airi27   24  Other / Non-Disclosed      163

                Item Name  Price
637  Thunderfury Scimitar   3.45
('Aisur51', 28, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
184          184  Aisur51   28   Male       32   Orenmir   1.14
('Aisurdru79', 29, 'Female')
     Purchase ID          SN  Age  Gender  Item ID                Item Name  \
440          440  Aisurdru79   29  Female       75  Brutality Ivory Warmace
618          618  Aisurdru79   29  Female      183      Dragon's Greatsword

     Price
440   2.42
618   1.09
('Aisurria69', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
423          423  Aisurria69   24   Male       10  Sleepwalker   1.79
('Aithelis62', 21, 'Male')
     Purchase ID          SN  Age Gender  Item ID              Item Name  \
703          703  Aithelis62   21   Male      160             Azurewrath
760          760  Aithelis62   21   Male       44  Bonecarvin Battle Axe

     Price
703   4.40
760   2.38
('Alaephos75', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
295          295  Alaephos75   23   Male       52    Hatred   4.84
('Alaesu77', 30, 'Male')
     Purchase ID        SN  Age Gender  Item ID     Item Name  Price
494          494  Alaesu77   30   Male        3  Phantomlight   2.49
('Alaesu91', 26, 'Male')
     Purchase ID        SN  Age Gender  Item ID             Item Name  Price
285          285  Alaesu91   26   Male      163  Thunderfury Scimitar   3.45
('Alarap40', 18, 'Male')
     Purchase ID        SN  Age Gender  Item ID   Item Name  Price
391          391  Alarap40   18   Male       20  Netherbane   3.27
('Ali84', 29, 'Male')
     Purchase ID     SN  Age Gender  Item ID           Item Name  Price
360          360  Ali84   29   Male       14      Possessed Core   2.61
635          635  Ali84   29   Male        4  Bloodlord's Fetish   1.70
('Alim85', 25, 'Male')
     Purchase ID      SN  Age Gender  Item ID        Item Name  Price
226          226  Alim85   25   Male       54  Eternal Cleaver    2.5
('Alo38', 20, 'Male')
    Purchase ID     SN  Age Gender  Item ID                   Item Name  Price
63           63  Alo38   20   Male      125  Whistling Mithril Warblade    1.0
('Anallorgue57', 8, 'Male')
     Purchase ID            SN  Age Gender  Item ID         Item Name  Price
272          272  Anallorgue57    8   Male      133  Faith's Scimitar   4.09
311          311  Anallorgue57    8   Male       71            Demise   1.61
('Ardcil81', 34, 'Male')
     Purchase ID        SN  Age Gender  Item ID                    Item Name  \
398          398  Ardcil81   34   Male       96  Blood-Forged Skeletal Spine
544          544  Ardcil81   34   Male        3                 Phantomlight

     Price
398   3.09
544   2.49
('Ardonmol96', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID  Item Name  Price
566          566  Ardonmol96   20   Male       31  Trickster   1.55
('Arin32', 25, 'Male')
     Purchase ID      SN  Age Gender  Item ID  \
627          627  Arin32   25   Male      178
734          734  Arin32   25   Male      165

                                        Item Name  Price
627  Oathbreaker, Last Hope of the Breaking Storm   4.23
734                   Bone Crushing Silver Skewer   4.86
('Arirgue63', 29, 'Male')
     Purchase ID         SN  Age Gender  Item ID           Item Name  Price
470          470  Arirgue63   29   Male        4  Bloodlord's Fetish    1.7
('Assassa81', 27, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
631          631  Assassa81   27   Male      137

                          Item Name  Price
631  Aetherius, Boon of the Blessed   3.39
('Assassasta79', 38, 'Male')
     Purchase ID            SN  Age Gender  Item ID       Item Name  Price
270          270  Assassasta79   38   Male       85  Malificent Bag   1.75
768          768  Assassasta79   38   Male       92    Final Critic   4.88
('Assastnya25', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
565          565  Assastnya25   20   Male      179

                           Item Name  Price
565  Wolf, Promise of the Moonwalker   4.48
('Assehoan67', 26, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
258          258  Assehoan67   26   Male      149

                             Item Name  Price
258  Tranquility, Razor of Black Magic   1.75
('Assesi91', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
420          420  Assesi91   23   Male      129

                              Item Name  Price
420  Fate, Vengeance of Eternal Justice   1.54
('Assilsan72', 20, 'Female')
     Purchase ID          SN  Age  Gender  Item ID Item Name  Price
666          666  Assilsan72   20  Female       82   Nirvana    4.9
('Assim27', 45, 'Male')
     Purchase ID       SN  Age Gender  Item ID                     Item Name  \
761          761  Assim27   45   Male       17  Lazarus, Terror of the Earth

     Price
761    1.7
('Assirra56', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
587          587  Assirra56   22   Male      141  Persuasion   3.19
('Assistasda42', 21, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
73            73  Assistasda42   21   Male       68
351          351  Assistasda42   21   Male      121

                             Item Name  Price
73   Storm-Weaver, Slayer of Inception   4.32
351                           Massacre   1.60
('Assistasda90', 25, 'Male')
     Purchase ID            SN  Age Gender  Item ID       Item Name  Price
460          460  Assistasda90   25   Male      103  Singed Scalpel   4.35
('Assjaskan56', 26, 'Male')
    Purchase ID           SN  Age Gender  Item ID             Item Name  Price
79           79  Assjaskan56   26   Male       15  Soul Infused Crystal   2.96
('Assjaskan73', 22, 'Male')
    Purchase ID           SN  Age Gender  Item ID           Item Name  Price
13           13  Assjaskan73   22   Male        4  Bloodlord's Fetish    1.7
('Assosia88', 20, 'Female')
    Purchase ID         SN  Age  Gender  Item ID  \
41           41  Assosia88   20  Female        7

                       Item Name  Price
41  Thorn, Satchel of Dark Souls   1.33
('Assylla81', 20, 'Male')
     Purchase ID         SN  Age Gender  Item ID         Item Name  Price
729          729  Assylla81   20   Male       74  Yearning Crusher   4.18
('Asty82', 25, 'Male')
     Purchase ID      SN  Age Gender  Item ID                    Item Name  \
680          680  Asty82   25   Male       96  Blood-Forged Skeletal Spine

     Price
680   3.09
('Asur53', 26, 'Male')
     Purchase ID      SN  Age Gender  Item ID                     Item Name  \
390          390  Asur53   26   Male       75       Brutality Ivory Warmace
762          762  Asur53   26   Male      110                    Suspension
772          772  Asur53   26   Male      136  Ghastly Adamantite Protector

     Price
390   2.42
762   1.44
772   3.58
('Asur96', 20, 'Male')
    Purchase ID      SN  Age Gender  Item ID                       Item Name  \
48           48  Asur96   20   Male      138  Peacekeeper, Wit of Dark Magic

    Price
48   4.74
('Baelollodeu94', 20, 'Female')
     Purchase ID             SN  Age  Gender  Item ID  \
178          178  Baelollodeu94   20  Female       57
569          569  Baelollodeu94   20  Female       87

                           Item Name  Price
178  Despair, Favor of Due Diligence   4.60
569         Deluge, Edge of the West   4.43
('Bartassaya73', 26, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
387          387  Bartassaya73   26   Male       39
644          644  Bartassaya73   26   Male       22

                                Item Name  Price
387  Betrayal, Whisper of Grieving Widows   3.94
644                               Amnesia   2.18
('Caesrinusuir82', 30, 'Male')
     Purchase ID              SN  Age Gender  Item ID  Item Name  Price
171          171  Caesrinusuir82   30   Male      102    Avenger   3.44
671          671  Caesrinusuir82   30   Male      152  Darkheart   1.74
('Ceoral34', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID             Item Name  Price
329          329  Ceoral34   20   Male      145  Fiery Glass Crusader   4.58
('Chadadarla74', 30, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
310          310  Chadadarla74   30   Male      117
614          614  Chadadarla74   30   Male       65

                             Item Name  Price
310  Heartstriker, Legacy of the Light   1.79
614          Conqueror Adamantite Mace   4.24
('Chadilsasta32', 23, 'Male')
     Purchase ID             SN  Age Gender  Item ID  \
331          331  Chadilsasta32   23   Male        7
343          343  Chadilsasta32   23   Male       49

                            Item Name  Price
331      Thorn, Satchel of Dark Souls   1.33
343  The Oculus, Token of Lost Worlds   2.96
('Chadirra90', 18, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
359          359  Chadirra90   18   Male       73  Ritual Mace   2.05
('Chadista79', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID                   Item Name  \
186          186  Chadista79   30   Male       77  Piety, Guardian of Riddles
506          506  Chadista79   30   Male       25                   Hero Cane

     Price
186   4.00
506   4.35
('Chadistaya75', 21, 'Female')
    Purchase ID            SN  Age  Gender  Item ID  \
92           92  Chadistaya75   21  Female       39

                               Item Name  Price
92  Betrayal, Whisper of Grieving Widows   3.94
('Chadjask77', 8, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
686          686  Chadjask77    8   Male      147

                             Item Name  Price
686  Hellreaver, Heirloom of Inception   4.93
('Chadjask85', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
647          647  Chadjask85   24   Male       61  Ragnarok   3.87
('Chadolyla44', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
91            91  Chadolyla44   20   Male       59
198          198  Chadolyla44   20   Male      153
711          711  Chadolyla44   20   Male       94

                         Item Name  Price
91   Lightning, Etcher of the King   4.23
198                Mercenary Sabre   3.74
711                 Mourning Blade   3.49
('Chadossa56', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
570          570  Chadossa56   20   Male       69

                           Item Name  Price
570  Frenzy, Defender of the Harvest   1.98

     Purchase ID            SN  Age  Gender  Item ID  Item Name  Price
347          347  Chamilsala65   23  Female       11  Brimstone   3.65
504          504  Chamilsala65   23  Female       82    Nirvana   4.90
('Chamiman85', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID           Item Name  Price
733          733  Chamiman85   20   Male       66  Victor Iron Spikes    4.4
('Chamimla73', 17, 'Male')
     Purchase ID          SN  Age Gender  Item ID                Item Name  \
176          176  Chamimla73   17   Male      157  Spada, Etcher of Hatred

     Price
176    4.8
('Chamimla85', 16, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
204          204  Chamimla85   16   Male        0
234          234  Chamimla85   16   Male       97
617          617  Chamimla85   16   Male       40

                       Item Name  Price
204                     Splinter   1.28
234  Swan Song, Gouger Of Terror   2.50
617                Second Chance   2.52
('Chamirra53', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID                Item Name  \
145          145  Chamirra53   23   Male       46  Hopeless Ebon Dualblade
256          256  Chamirra53   23   Male      182                Toothpick

     Price
145   1.33
256   4.03
('Chamirrasya33', 21, 'Female')
     Purchase ID             SN  Age  Gender  Item ID   Item Name  Price
384          384  Chamirrasya33   21  Female      110  Suspension   1.44
404          404  Chamirrasya33   21  Female       71      Demise   1.61
('Chamirraya83', 25, 'Male')
    Purchase ID            SN  Age Gender  Item ID        Item Name  Price
65           65  Chamirraya83   25   Male       34  Retribution Axe   2.22
('Chamistast30', 31, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
664          664  Chamistast30   31   Male       47

                       Item Name  Price
664  Alpha, Reach of Ending Hope   3.58
('Chamjask73', 22, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
222          222  Chamjask73   22  Female      178
520          520  Chamjask73   22  Female      109
564          564  Chamjask73   22  Female       52

                                        Item Name  Price
222  Oathbreaker, Last Hope of the Breaking Storm   4.23
520              Downfall, Scalpel Of The Emperor   4.76
564                                        Hatred   4.84
('Chamjaskya75', 16, 'Male')
     Purchase ID            SN  Age Gender  Item ID               Item Name  \
611          611  Chamjaskya75   16   Male      176  Relentless Iron Skewer

     Price
611   2.84
('Chamossa77', 21, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
433          433  Chamossa77   21   Male      156

                        Item Name  Price
433  Soul-Forged Steel Shortsword   1.77
('Chanadar44', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID   Item Name  Price
538          538  Chanadar44   25   Male      141  Persuasion   3.19
('Chanastnya43', 22, 'Male')
     Purchase ID            SN  Age Gender  Item ID                 Item Name  \
507          507  Chanastnya43   22   Male       29   Chaos, Ender of the End
561          561  Chanastnya43   22   Male       35  Heartless Bone Dualblade
633          633  Chanastnya43   22   Male       80                 Dreamsong

     Price
507   1.98
561   3.45
633   3.39
('Chanastsda67', 21, 'Female')
    Purchase ID            SN  Age  Gender  Item ID    Item Name  Price
66           66  Chanastsda67   21  Female        6  Rusty Skull    3.7
('Chanastst38', 22, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
164          164  Chanastst38   22   Male       96
744          744  Chanastst38   22   Male       94

                       Item Name  Price
164  Blood-Forged Skeletal Spine   3.09
744               Mourning Blade   3.49
('Chanastya70', 22, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
300          300  Chanastya70   22   Male      136

                        Item Name  Price
300  Ghastly Adamantite Protector   3.58
('Chanilsasda38', 15, 'Male')
     Purchase ID             SN  Age Gender  Item ID      Item Name  Price
668          668  Chanilsasda38   15   Male       40  Second Chance   2.52
('Chanilsast61', 30, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
717          717  Chanilsast61   30   Male      177

                                    Item Name  Price
717  Winterthorn, Defender of Shifting Worlds   2.08
('Chanirra64', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
622          622  Chanirra64   25   Male      129

                              Item Name  Price
622  Fate, Vengeance of Eternal Justice   1.54
('Chanirra79', 23, 'Female')
     Purchase ID          SN  Age  Gender  Item ID                  Item Name  \
586          586  Chanirra79   23  Female      155  War-Forged Gold Deflector

     Price
586   1.01
('Chanirrala39', 22, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
585          585  Chanirrala39   22   Male       85
636          636  Chanirrala39   22   Male       78

                      Item Name  Price
585              Malificent Bag   1.75
636  Glimmer, Ender of the Moon   4.40
('Chanirrasta87', 14, 'Male')
     Purchase ID             SN  Age Gender  Item ID                Item Name  \
493          493  Chanirrasta87   14   Male      139  Mercy, Katana of Dismay

     Price
493   4.94
('Chanista95', 39, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
745          745  Chanista95   39   Male       37

                               Item Name  Price
745  Shadow Strike, Glory of Ending Hope   3.16
('Chanjask65', 18, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
448          448  Chanjask65   18  Female       68

                             Item Name  Price
448  Storm-Weaver, Slayer of Inception   4.32
('Chanjaskan89', 21, 'Male')
     Purchase ID            SN  Age Gender  Item ID         Item Name  Price
153          153  Chanjaskan89   21   Male      164  Exiled Doomblade   1.63
479          479  Chanjaskan89   21   Male       60              Wolf   3.54
('Chanosia34', 22, 'Male')
    Purchase ID          SN  Age Gender  Item ID             Item Name  Price
51           51  Chanosia34   22   Male       15  Soul Infused Crystal   2.96
('Chanosia60', 31, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
201          201  Chanosia60   31   Male        2   Verdict   2.48
700          700  Chanosia60   31   Male       90  Betrayer   2.94
('Chanosian48', 35, 'Other / Non-Disclosed')
     Purchase ID           SN  Age                 Gender  Item ID  \
9              9  Chanosian48   35  Other / Non-Disclosed      136
484          484  Chanosian48   35  Other / Non-Disclosed       39

                                Item Name  Price
9            Ghastly Adamantite Protector   3.58
484  Betrayal, Whisper of Grieving Widows   3.94
('Chanosiaya39', 44, 'Male')
     Purchase ID            SN  Age Gender  Item ID                 Item Name  \
728          728  Chanosiaya39   44   Male       93  Apocalyptic Battlescythe

     Price
728   1.97
('Chanossanya44', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID  \
706          706  Chanossanya44   20   Male      178
749          749  Chanossanya44   20   Male       53

                                        Item Name  Price
706  Oathbreaker, Last Hope of the Breaking Storm   4.23
749                             Vengeance Cleaver   2.05
('Chanossast57', 7, 'Female')
     Purchase ID            SN  Age  Gender  Item ID  \
446          446  Chanossast57    7  Female      119

                                     Item Name  Price
446  Stormbringer, Dark Blade of Ending Misery   4.32
('Chanuchi25', 20, 'Male')
    Purchase ID          SN  Age Gender  Item ID    Item Name  Price
47           47  Chanuchi25   20   Male      170  Shadowsteel   3.97
('Cosadar58', 38, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
217          217  Cosadar58   38   Male       25  Hero Cane   4.35
('Dyally87', 22, 'Male')
     Purchase ID        SN  Age Gender  Item ID       Item Name  Price
554          554  Dyally87   22   Male       63  Stormfury Mace   4.99
('Ealiril69', 35, 'Male')
     Purchase ID         SN  Age Gender  Item ID                   Item Name  \
687          687  Ealiril69   35   Male       78  Glimmer, Ender of the Moon

     Price
687    4.4
('Ealrion88', 30, 'Male')
     Purchase ID         SN  Age Gender  Item ID                   Item Name  \
221          221  Ealrion88   30   Male      175  Woeful Adamantite Claymore

     Price
221   4.48
('Ennalmol65', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID     Item Name  Price
277          277  Ennalmol65   24   Male       92  Final Critic   4.88
('Ennoncil86', 17, 'Male')
     Purchase ID          SN  Age Gender  Item ID  Item Name  Price
395          395  Ennoncil86   17   Male      152  Darkheart   1.74
('Ennrian78', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
461          461  Ennrian78   24   Male      168
779          779  Ennrian78   24   Male       50

                               Item Name  Price
461  Sun Strike, Jaws of Twisted Visions   1.48
779                                 Dawn   4.60
('Eodailis27', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
239          239  Eodailis27   30   Male       19
367          367  Eodailis27   30   Male      138

                          Item Name  Price
239   Pursuit, Cudgel of Necromancy   1.02
367  Peacekeeper, Wit of Dark Magic   4.74
('Eodairu79', 32, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
501          501  Eodairu79   32   Male      151  Severance    3.4
('Eodaisu60', 16, 'Other / Non-Disclosed')
     Purchase ID         SN  Age                 Gender  Item ID  \
242          242  Eodaisu60   16  Other / Non-Disclosed       39

                                Item Name  Price
242  Betrayal, Whisper of Grieving Widows   3.94
('Eolan54', 30, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
459          459  Eolan54   30   Male      129

                              Item Name  Price
459  Fate, Vengeance of Eternal Justice   1.54
('Eoral49', 16, 'Male')
     Purchase ID       SN  Age Gender  Item ID       Item Name  Price
634          634  Eoral49   16   Male      103  Singed Scalpel   4.35
('Eoralrap26', 22, 'Male')
    Purchase ID          SN  Age Gender  Item ID  \
89           89  Eoralrap26   22   Male       17

                       Item Name  Price
89  Lazarus, Terror of the Earth    1.7
('Eosrirgue62', 17, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
211          211  Eosrirgue62   17   Male      120    Agatha   3.08
('Eosurdru76', 11, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
539          539  Eosurdru76   11   Male      117

                             Item Name  Price
539  Heartstriker, Legacy of the Light   1.79
('Eratiel90', 18, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
757          757  Eratiel90   18   Male       57

                           Item Name  Price
757  Despair, Favor of Due Diligence    4.6
('Ermol76', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID                    Item Name  \
495          495  Ermol76   24   Male       97  Swan Song, Gouger Of Terror

     Price
495    2.5
('Errian63', 26, 'Female')
     Purchase ID        SN  Age  Gender  Item ID       Item Name  Price
485          485  Errian63   26  Female       94  Mourning Blade   3.49
('Eryon48', 16, 'Male')
     Purchase ID       SN  Age Gender  Item ID  Item Name  Price
532          532  Eryon48   16   Male       21  Souleater    1.1
('Ethralista69', 13, 'Male')
     Purchase ID            SN  Age Gender  Item ID        Item Name  Price
449          449  Ethralista69   13   Male       34  Retribution Axe   2.22
('Ethrasyon38', 26, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
656          656  Ethrasyon38   26   Male      115

                      Item Name  Price
656  Spectral Diamond Doomblade   2.04
('Ethriel85', 30, 'Male')
     Purchase ID         SN  Age Gender  Item ID             Item Name  Price
135          135  Ethriel85   30   Male      146  Warped Iron Scimitar    3.1
('Ethron58', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID     Item Name  Price
368          368  Ethron58   20   Male        3  Phantomlight   2.49
('Eudanu32', 15, 'Female')
     Purchase ID        SN  Age  Gender  Item ID         Item Name  Price
451          451  Eudanu32   15  Female      122  Unending Tyranny   2.85
('Eudanu84', 22, 'Female')
     Purchase ID        SN  Age  Gender  Item ID Item Name  Price
731          731  Eudanu84   22  Female       12     Dawne   1.02
('Eulae84', 25, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
457          457  Eulae84   25   Male       61  Ragnarok   3.87
('Eulaestira36', 18, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
288          288  Eulaestira36   18   Male      156
348          348  Eulaestira36   18   Male       38

                             Item Name  Price
288       Soul-Forged Steel Shortsword   1.77
348  The Void, Vengeance of Dark Magic   2.37
('Eulanurin88', 27, 'Male')
     Purchase ID           SN  Age Gender  Item ID    Item Name  Price
105          105  Eulanurin88   27   Male       10  Sleepwalker   1.79
('Eulasuir89', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID      Item Name  Price
209          209  Eulasuir89   22   Male      162  Abyssal Shard   2.67
('Eulolis41', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID      Item Name  Price
510          510  Eulolis41   22   Male      162  Abyssal Shard   2.67
('Eurisuru25', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
638          638  Eurisuru25   24   Male       22   Amnesia   2.18
('Eurithphos97', 9, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
486          486  Eurithphos97    9   Male       53
732          732  Eurithphos97    9   Male       97

                       Item Name  Price
486            Vengeance Cleaver   2.05
732  Swan Song, Gouger Of Terror   2.50
('Eusri26', 25, 'Male')
     Purchase ID       SN  Age Gender  Item ID    Item Name  Price
397          397  Eusri26   25   Male      100  Blindscythe   3.27
('Eusri44', 7, 'Male')
    Purchase ID       SN  Age Gender  Item ID                    Item Name  \
27           27  Eusri44    7   Male       96  Blood-Forged Skeletal Spine

    Price
27   3.09
('Eusri70', 24, 'Female')
     Purchase ID       SN  Age  Gender  Item ID     Item Name  Price
422          422  Eusri70   24  Female      154  Feral Katana   4.40
519          519  Eusri70   24  Female      140       Striker   2.94
('Eustyria89', 39, 'Male')
     Purchase ID          SN  Age Gender  Item ID  Item Name  Price
648          648  Eustyria89   39   Male      150  Deathraze   2.85
('Eusur90', 36, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
738          738  Eusur90   36   Male      121  Massacre    1.6
('Eusurdeu49', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID                  Item Name  \
371          371  Eusurdeu49   23   Male      155  War-Forged Gold Deflector
715          715  Eusurdeu49   23   Male        8   Purgatory, Gem of Regret

     Price
371   1.01
715   3.93
('Euthe35', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID   Item Name  Price
453          453  Euthe35   24   Male       70  Hope's End   1.03
('Eyircil84', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
473          473  Eyircil84   21   Male       25  Hero Cane   4.35
('Eyista89', 34, 'Male')
     Purchase ID        SN  Age Gender  Item ID       Item Name  Price
143          143  Eyista89   34   Male      124  Venom Claymore   1.29
('Eyrian71', 40, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
23            23  Eyrian71   40   Male      151
156          156  Eyrian71   40   Male      117

                             Item Name  Price
23                           Severance   3.40
156  Heartstriker, Legacy of the Light   1.79
('Farrian71', 18, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
605          605  Farrian71   18   Male      159

                             Item Name  Price
605  Oathbreaker, Spellblade of Trials   3.08
('Farusrian86', 37, 'Male')
    Purchase ID           SN  Age Gender  Item ID  \
31           31  Farusrian86   37   Male      179

                          Item Name  Price
31  Wolf, Promise of the Moonwalker   4.48
('Filrion59', 27, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
594          594  Filrion59   27   Male       89

                             Item Name  Price
594  Blazefury, Protector of Delusions   4.64
('Filrion83', 17, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
632          632  Filrion83   17   Male      160  Azurewrath    4.4
('Filurarn35', 19, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
577          577  Filurarn35   19   Male      128

                         Item Name  Price
577  Blazeguard, Reach of Eternity   4.91
('Firan91', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID                      Item Name  \
284          284  Firan91   24   Male      128  Blazeguard, Reach of Eternity

     Price
284   4.91
('Firatan58', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
693          693  Firatan58   23   Male       88

                            Item Name  Price
693  Emberling, Defender of Delusions   3.75
('Firon67', 35, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
498          498  Firon67   35   Male      108

                                     Item Name  Price
498  Extraction, Quickblade Of Trembling Hands   3.53
('Fironon91', 30, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
173          173  Fironon91   30   Male        5  Putrid Fan   4.08
('Frichadar89', 24, 'Male')
     Purchase ID           SN  Age Gender  Item ID      Item Name  Price
403          403  Frichadar89   24   Male      162  Abyssal Shard   2.67
('Frichadaran88', 25, 'Male')
     Purchase ID             SN  Age Gender  Item ID  \
301          301  Frichadaran88   25   Male      106
463          463  Frichadaran88   25   Male       48

                           Item Name  Price
301              Crying Steel Sickle   3.41
463  Rage, Legacy of the Lone Victor   2.48
('Frichast28', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
194          194  Frichast28   20   Male       73  Ritual Mace   2.05
('Frichaststa61', 21, 'Female')
     Purchase ID             SN  Age  Gender  Item ID  \
117          117  Frichaststa61   21  Female      117

                             Item Name  Price
117  Heartstriker, Legacy of the Light   1.79
('Frichaya88', 42, 'Male')
     Purchase ID          SN  Age Gender  Item ID                 Item Name  \
557          557  Frichaya88   42   Male        8  Purgatory, Gem of Regret

     Price
557   3.93
('Frichilsa31', 15, 'Male')
     Purchase ID           SN  Age Gender  Item ID   Item Name  Price
743          743  Frichilsa31   15   Male      110  Suspension   1.44
('Frichim77', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
103          103  Frichim77   24   Male        7
126          126  Frichim77   24   Male       75

                        Item Name  Price
103  Thorn, Satchel of Dark Souls   1.33
126       Brutality Ivory Warmace   2.42
('Frichirranya75', 36, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
753          753  Frichirranya75   36   Male      178

                                        Item Name  Price

     Purchase ID             SN  Age Gender  Item ID  \
610          610  Frichossala54    7   Male      159

                             Item Name  Price
610  Oathbreaker, Spellblade of Trials   3.08
('Frichynde86', 15, 'Male')
     Purchase ID           SN  Age Gender  Item ID         Item Name  Price
430          430  Frichynde86   15   Male      164  Exiled Doomblade   1.63
('Hada39', 19, 'Male')
     Purchase ID      SN  Age Gender  Item ID  \
345          345  Hada39   19   Male        2
533          533  Hada39   19   Male       48
628          628  Hada39   19   Male      167

                           Item Name  Price
345                          Verdict   2.48
533  Rage, Legacy of the Lone Victor   2.48
628      Malice, Legacy of the Queen   3.61
('Haedairiadru51', 23, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
378          378  Haedairiadru51   23   Male       96

                       Item Name  Price
378  Blood-Forged Skeletal Spine   3.09
('Haeladil46', 18, 'Male')
     Purchase ID          SN  Age Gender  Item ID      Item Name  Price
227          227  Haeladil46   18   Male       24  Warped Fetish   3.81
('Haellysu29', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID      Item Name  Price
259          259  Haellysu29   20   Male       72  Winter's Bite   3.77
('Haerith37', 23, 'Male')
    Purchase ID         SN  Age Gender  Item ID      Item Name  Price
45           45  Haerith37   23   Male      181  Reaper's Toll   1.66
('Haerithp41', 16, 'Other / Non-Disclosed')
    Purchase ID          SN  Age                 Gender  Item ID   Item Name  \
82           82  Haerithp41   16  Other / Non-Disclosed      160  Azurewrath

    Price
82    4.4
('Haestyphos66', 21, 'Male')
     Purchase ID            SN  Age Gender  Item ID                 Item Name  \
643          643  Haestyphos66   21   Male       93  Apocalyptic Battlescythe

     Price
643   1.97
('Hailaphos89', 35, 'Male')
     Purchase ID           SN  Age Gender  Item ID      Item Name  Price
147          147  Hailaphos89   35   Male       24  Warped Fetish   3.81
('Haillyrgue51', 7, 'Male')
     Purchase ID            SN  Age Gender  Item ID              Item Name  \
33            33  Haillyrgue51    7   Male       44  Bonecarvin Battle Axe
78            78  Haillyrgue51    7   Male       50                   Dawn
515          515  Haillyrgue51    7   Male       40          Second Chance

     Price
33    2.38
78    4.60
515   2.52
('Haisrisuir60', 23, 'Male')
    Purchase ID            SN  Age Gender  Item ID      Item Name  Price
11           11  Haisrisuir60   23   Male      162  Abyssal Shard   2.67
99           99  Haisrisuir60   23   Male      101   Final Critic   4.19
('Haisurra41', 20, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
206          206  Haisurra41   20  Female       78

                      Item Name  Price
206  Glimmer, Ender of the Moon    4.4
('Hala31', 21, 'Male')
     Purchase ID      SN  Age Gender  Item ID                      Item Name  \
773          773  Hala31   21   Male       19  Pursuit, Cudgel of Necromancy

     Price
773   1.02
('Halaecal66', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID        Item Name  Price
598          598  Halaecal66   22   Male      111     Misery's End   4.89
685          685  Halaecal66   22   Male       34  Retribution Axe   2.22
('Hallysucal81', 25, 'Male')
     Purchase ID            SN  Age Gender  Item ID      Item Name  Price
375          375  Hallysucal81   25   Male      181  Reaper's Toll   1.66
('Hari50', 20, 'Female')
     Purchase ID      SN  Age  Gender  Item ID                 Item Name  \
71            71  Hari50   20  Female       29   Chaos, Ender of the End
140          140  Hari50   20  Female        8  Purgatory, Gem of Regret

     Price
71    1.98
140   3.93
('Hariphos58', 17, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
665          665  Hariphos58   17   Male       73  Ritual Mace   2.05
('Heollyra92', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID            Item Name  Price
271          271  Heollyra92   22   Male      166  Thirsty Iron Reaver   3.07
('Heollyriap59', 21, 'Male')
     Purchase ID            SN  Age Gender  Item ID        Item Name  Price
101          101  Heollyriap59   21   Male      174  Primitive Blade   3.47
('Heosurnuru52', 16, 'Female')
     Purchase ID            SN  Age  Gender  Item ID  \
169          169  Heosurnuru52   16  Female      123
297          297  Heosurnuru52   16  Female      169

                                  Item Name  Price
169                       Twilight's Carver   2.28
297  Interrogator, Blood Blade of the Queen   2.18
('Heudai45', 8, 'Female')
    Purchase ID        SN  Age  Gender  Item ID        Item Name  Price
81           81  Heudai45    8  Female      174  Primitive Blade   3.47
('Heuli25', 23, 'Female')
     Purchase ID       SN  Age  Gender  Item ID  \
357          357  Heuli25   23  Female       37
369          369  Heuli25   23  Female      137

                               Item Name  Price
357  Shadow Strike, Glory of Ending Hope   3.16
369       Aetherius, Boon of the Blessed   3.39
('Heunadil74', 23, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
402          402  Heunadil74   23  Female      129

                              Item Name  Price
402  Fate, Vengeance of Eternal Justice   1.54
('Hiaral50', 15, 'Male')
     Purchase ID        SN  Age Gender  Item ID                     Item Name  \
441          441  Hiaral50   15   Male      156  Soul-Forged Steel Shortsword
552          552  Hiaral50   15   Male      155     War-Forged Gold Deflector
599          599  Hiaral50   15   Male       13                      Serenity

     Price
441   1.77
552   1.01
599   1.41
('Hiarideu73', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID        Item Name  Price
393          393  Hiarideu73   20   Male       54  Eternal Cleaver    2.5
('Hiasri33', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID        Item Name  Price
189          189  Hiasri33   23   Male       63   Stormfury Mace   4.99
325          325  Hiasri33   23   Male       54  Eternal Cleaver   2.50
('Hiasurria41', 41, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
341          341  Hiasurria41   41   Male       71    Demise   1.61
('Hilaerin92', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
330          330  Hilaerin92   23   Male      167

                       Item Name  Price
330  Malice, Legacy of the Queen   3.61
('Hiral75', 22, 'Male')
     Purchase ID       SN  Age Gender  Item ID                Item Name  Price
385          385  Hiral75   22   Male       29  Chaos, Ender of the End   1.98
('Hirirap39', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
109          109  Hirirap39   22   Male       33  Curved Axe   1.16
366          366  Hirirap39   22   Male       31   Trickster   1.55
('Hisridru55', 18, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
432          432  Hisridru55   18   Male      120    Agatha   3.08
('Hyaduesu61', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
154          154  Hyaduesu61   20   Male       59

                         Item Name  Price
154  Lightning, Etcher of the King   4.23
('Iadueria43', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
499          499  Iadueria43   24   Male       99

                                Item Name  Price
499  Expiration, Warscythe Of Lost Worlds   1.71
('Ialallo29', 15, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
199          199  Ialallo29   15  Female      138
215          215  Ialallo29   15  Female       40
683          683  Ialallo29   15  Female      145

                          Item Name  Price
199  Peacekeeper, Wit of Dark Magic   4.74
215                   Second Chance   2.52
683            Fiery Glass Crusader   4.58
('Ialidru40', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
314          314  Ialidru40   24   Male       37

                               Item Name  Price
314  Shadow Strike, Glory of Ending Hope   3.16
('Iana95', 10, 'Male')
     Purchase ID      SN  Age Gender  Item ID             Item Name  Price
534          534  Iana95   10   Male      146  Warped Iron Scimitar    3.1
('Iarallo65', 26, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
443          443  Iarallo65   26   Male      149

                             Item Name  Price
443  Tranquility, Razor of Black Magic   1.75
('Iaralrgue74', 33, 'Male')
     Purchase ID           SN  Age Gender  Item ID   Item Name  Price
49            49  Iaralrgue74   33   Male      110  Suspension   1.44
419          419  Iaralrgue74   33   Male      171     Scalpel   1.79
('Iaralsuir44', 23, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
214          214  Iaralsuir44   23   Male      137
503          503  Iaralsuir44   23   Male       59

                          Item Name  Price
214  Aetherius, Boon of the Blessed   3.39
503   Lightning, Etcher of the King   4.23
('Iarilis73', 10, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
424          424  Iarilis73   10   Male      149
679          679  Iarilis73   10   Male      153

                             Item Name  Price
424  Tranquility, Razor of Black Magic   1.75
679                    Mercenary Sabre   3.74
('Iasrira89', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID        Item Name  Price
313          313  Iasrira89   23   Male      182        Toothpick   4.03
559          559  Iasrira89   23   Male       34  Retribution Axe   2.22
('Iasur80', 22, 'Male')
     Purchase ID       SN  Age Gender  Item ID                Item Name  Price
251          251  Iasur80   22   Male       23                 Crucifer   1.99
713          713  Iasur80   22   Male       46  Hopeless Ebon Dualblade   1.33
('Iasurriacal29', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID          Item Name  Price
591          591  Iasurriacal29   20   Male      113  Solitude's Reaver   4.07
('Iasursti71', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID      Item Name  Price
304          304  Iasursti71   24   Male      181  Reaper's Toll   1.66
('Iathem87', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID   Item Name  Price
590          590  Iathem87   20   Male      141  Persuasion   3.19
('Iathenudil29', 20, 'Male')
    Purchase ID            SN  Age Gender  Item ID  \
20           20  Iathenudil29   20   Male       57

                          Item Name  Price
20  Despair, Favor of Due Diligence    4.6
('Idacal95', 30, 'Male')
     Purchase ID        SN  Age Gender  Item ID Item Name  Price
673          673  Idacal95   30   Male      130     Alpha   2.07
('Idai61', 19, 'Male')
     Purchase ID      SN  Age Gender  Item ID            Item Name  Price
30            30  Idai61   19   Male      140              Striker   2.94
370          370  Idai61   19   Male       45  Glinting Glass Edge   3.85
407          407  Idai61   19   Male      131                 Fury   1.44
('Idaidil28', 15, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
406          406  Idaidil28   15   Male      100
690          690  Idaidil28   15   Male       68

                             Item Name  Price
406                        Blindscythe   3.27
690  Storm-Weaver, Slayer of Inception   4.32
('Idairin51', 20, 'Other / Non-Disclosed')
     Purchase ID         SN  Age                 Gender  Item ID  \
237          237  Idairin51   20  Other / Non-Disclosed       16
291          291  Idairin51   20  Other / Non-Disclosed       35

                    Item Name  Price
237           Restored Bauble   3.55
291  Heartless Bone Dualblade   3.45
('Idaisuir85', 30, 'Male')
    Purchase ID          SN  Age Gender  Item ID                 Item Name  \
36           36  Idaisuir85   30   Male       76  Haunted Bronzed Bludgeon

    Price
36   3.15
('Idastidru52', 24, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
290          290  Idastidru52   24   Male      147
490          490  Idastidru52   24   Male      148
543          543  Idastidru52   24   Male      121
676          676  Idastidru52   24   Male      111

                              Item Name  Price
290   Hellreaver, Heirloom of Inception   4.93
490  Warmonger, Gift of Suffering's End   4.03
543                            Massacre   1.60
676                        Misery's End   4.89
('Iduelis31', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
726          726  Iduelis31   23   Male       21  Souleater    1.1
('Iduenu77', 17, 'Female')
     Purchase ID        SN  Age  Gender  Item ID           Item Name  Price
333          333  Iduenu77   17  Female      114  Yearning Mageblade   3.82
('Ilaesudil92', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID  Item Name  Price
513          513  Ilaesudil92   25   Male       25  Hero Cane   4.35
('Ilarin91', 22, 'Male')
     Purchase ID        SN  Age Gender  Item ID            Item Name  Price
352          352  Ilarin91   22   Male       79  Alpha, Oath of Zeal   4.05
400          400  Ilarin91   22   Male       72        Winter's Bite   3.77
722          722  Ilarin91   22   Male       92         Final Critic   4.88
('Ilassa51', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID        Item Name  Price
576          576  Ilassa51   20   Male       34  Retribution Axe   2.22
('Ilassast39', 18, 'Male')
    Purchase ID          SN  Age Gender  Item ID         Item Name  Price
95           95  Ilassast39   18   Male      164  Exiled Doomblade   1.63
('Ilast79', 20, 'Male')
     Purchase ID       SN  Age Gender  Item ID    Item Name  Price
756          756  Ilast79   20   Male       73  Ritual Mace   2.05
('Ilastilis78', 11, 'Male')
     Purchase ID           SN  Age Gender  Item ID                 Item Name  \
601          601  Ilastilis78   11   Male       93  Apocalyptic Battlescythe

     Price
601   1.97
('Ili43', 18, 'Male')
     Purchase ID     SN  Age Gender  Item ID Item Name  Price
144          144  Ili43   18   Male       22   Amnesia   2.18
('Ililsan66', 9, 'Male')
     Purchase ID         SN  Age Gender  Item ID         Item Name  Price
672          672  Ililsan66    9   Male      122  Unending Tyranny   2.85
('Ililsasya43', 19, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
702          702  Ililsasya43   19   Male       12     Dawne   1.02
('Ilimya66', 33, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
376          376  Ilimya66   33   Male       59

                         Item Name  Price
376  Lightning, Etcher of the King   4.23
('Ilirrasda54', 37, 'Male')
     Purchase ID           SN  Age Gender  Item ID   Item Name  Price
294          294  Ilirrasda54   37   Male      171     Scalpel   1.79
718          718  Ilirrasda54   37   Male       20  Netherbane   3.27
('Ilista82', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID Item Name  Price
426          426  Ilista82   23   Male       32   Orenmir   1.14
('Iljask75', 22, 'Male')
     Purchase ID        SN  Age Gender  Item ID                    Item Name  \
750          750  Iljask75   22   Male      167  Malice, Legacy of the Queen

     Price
750   3.61
('Ilmol66', 8, 'Female')
     Purchase ID       SN  Age  Gender  Item ID       Item Name  Price
339          339  Ilmol66    8  Female      124  Venom Claymore   1.29
767          767  Ilmol66    8  Female       92    Final Critic   4.88
('Ilosia37', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID         Item Name  Price
121          121  Ilosia37   23   Male        1          Crucifer   3.26
526          526  Ilosia37   23   Male      133  Faith's Scimitar   4.09
('Ilosian36', 15, 'Male')
     Purchase ID         SN  Age Gender  Item ID             Item Name  Price
769          769  Ilosian36   15   Male      145  Fiery Glass Crusader   4.58
('Ilosianya35', 32, 'Male')
    Purchase ID           SN  Age Gender  Item ID               Item Name  \
53           53  Ilosianya35   32   Male      176  Relentless Iron Skewer

    Price
53   2.84
('Ilunyon70', 20, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
550          550  Ilunyon70   20   Male       60      Wolf   3.54
('Ina92', 31, 'Male')
     Purchase ID     SN  Age Gender  Item ID             Item Name  Price
474          474  Ina92   31   Male      145  Fiery Glass Crusader   4.58
('Inasti31', 17, 'Male')
     Purchase ID        SN  Age Gender  Item ID Item Name  Price
150          150  Inasti31   17   Male        0  Splinter   1.28
268          268  Inasti31   17   Male       71    Demise   1.61
('Inasuir29', 40, 'Female')
     Purchase ID         SN  Age  Gender  Item ID           Item Name  Price
667          667  Inasuir29   40  Female       66  Victor Iron Spikes    4.4
('Indcil77', 17, 'Male')
     Purchase ID        SN  Age Gender  Item ID       Item Name  Price
175          175  Indcil77   17   Male      103  Singed Scalpel   4.35
('Indirrian56', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
721          721  Indirrian56   20   Male      156

                        Item Name  Price
721  Soul-Forged Steel Shortsword   1.77
('Indonmol95', 15, 'Male')
    Purchase ID          SN  Age Gender  Item ID  \
68           68  Indonmol95   15   Male       27

                          Item Name  Price
68  Riddle, Tribute of Ended Dreams    3.3
('Ingatcil75', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID          Item Name  Price
492          492  Ingatcil75   23   Male      143  Frenzied Scimitar   1.56
('Inguron55', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
10            10  Inguron55   23   Male       95
132          132  Inguron55   23   Male      145
509          509  Inguron55   23   Male      117

                             Item Name  Price
10               Singed Onyx Warscythe   4.74
132               Fiery Glass Crusader   4.58
509  Heartstriker, Legacy of the Light   1.79
('Iral74', 21, 'Male')
     Purchase ID      SN  Age Gender  Item ID  \
128          128  Iral74   21   Male       58
623          623  Iral74   21   Male      114
758          758  Iral74   21   Male      182
776          776  Iral74   21   Male      164

                             Item Name  Price
128  Freak's Bite, Favor of Holy Might   4.14
623                 Yearning Mageblade   3.82
758                          Toothpick   4.03
776                   Exiled Doomblade   1.63
('Iri67', 20, 'Male')
     Purchase ID     SN  Age Gender  Item ID                        Item Name  \
137          137  Iri67   20   Male      179  Wolf, Promise of the Moonwalker
161          161  Iri67   20   Male        3                     Phantomlight
551          551  Iri67   20   Male      160                       Azurewrath

     Price
137   4.48
161   2.49
551   4.40
('Irilis75', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
582          582  Irilis75   20   Male       19

                         Item Name  Price
582  Pursuit, Cudgel of Necromancy   1.02
('Irillo49', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID   Item Name  Price
434          434  Irillo49   20   Male       84  Arcane Gem   3.79
('Irith83', 18, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
765          765  Irith83   18   Male      130     Alpha   2.07
('Irithlis29', 23, 'Male')
    Purchase ID          SN  Age Gender  Item ID                    Item Name  \
80           80  Irithlis29   23   Male      165  Bone Crushing Silver Skewer

    Price
80   4.86
('Iskadarya95', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
148          148  Iskadarya95   20   Male      148

     Purchase ID            SN  Age Gender  Item ID                Item Name  \
116          116  Lassilsala30   21   Male      139  Mercy, Katana of Dismay
511          511  Lassilsala30   21   Male       64            Fusion Pummel
763          763  Lassilsala30   21   Male       85           Malificent Bag

     Price
116   4.94
511   4.82
763   1.75
('Lassimla92', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
454          454  Lassimla92   25   Male        1
593          593  Lassimla92   25   Male      128

                         Item Name  Price
454                       Crucifer   3.26
593  Blazeguard, Reach of Eternity   4.91
('Lassirrasda85', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID Item Name  Price
567          567  Lassirrasda85   20   Male      102   Avenger   3.44
('Lassjask63', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID               Item Name  \
174          174  Lassjask63   30   Male      144  Blood Infused Guardian

     Price
174   1.94
('Lassjaskan73', 22, 'Male')
     Purchase ID            SN  Age Gender  Item ID        Item Name  Price
106          106  Lassjaskan73   22   Male       54  Eternal Cleaver    2.5
('Layjask75', 22, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
327          327  Layjask75   22  Female       17

                        Item Name  Price
327  Lazarus, Terror of the Earth    1.7
('Leetirraya83', 24, 'Male')
     Purchase ID            SN  Age Gender  Item ID        Item Name  Price
530          530  Leetirraya83   24   Male        5       Putrid Fan   4.08
735          735  Leetirraya83   24   Male       54  Eternal Cleaver   2.50
('Leyirra83', 24, 'Female')
     Purchase ID         SN  Age  Gender  Item ID    Item Name  Price
427          427  Leyirra83   24  Female      170  Shadowsteel   3.97
608          608  Leyirra83   24  Female      132   Persuasion   3.33
('Liawista80', 27, 'Male')
     Purchase ID          SN  Age Gender  Item ID          Item Name  Price
639          639  Liawista80   27   Male       86  Stormfury Lantern   2.27
('Lirtassa52', 15, 'Male')
     Purchase ID          SN  Age Gender  Item ID            Item Name  Price
165          165  Lirtassa52   15   Male      183  Dragon's Greatsword   1.09
('Lirtassan78', 15, 'Male')
     Purchase ID           SN  Age Gender  Item ID   Item Name  Price
655          655  Lirtassan78   15   Male       20  Netherbane   3.27
('Lirtastan49', 29, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
213          213  Lirtastan49   29   Male        2   Verdict   2.48
('Lirtastsda29', 16, 'Male')
     Purchase ID            SN  Age Gender  Item ID               Item Name  \
240          240  Lirtastsda29   16   Male       82                 Nirvana
675          675  Lirtastsda29   16   Male      144  Blood Infused Guardian

     Price
240   4.90
675   1.94
('Lirtastsya71', 21, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
435          435  Lirtastsya71   21   Male       93
708          708  Lirtastsya71   21   Male       67

                                 Item Name  Price
435               Apocalyptic Battlescythe   1.97
708  Celeste, Incarnation of the Corrupted   3.46
('Lirtilsa71', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID                Item Name  \
246          246  Lirtilsa71   24   Male      139  Mercy, Katana of Dismay

     Price
246   4.94
('Lirtilsa72', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID                   Item Name  \
320          320  Lirtilsa72   24   Male       77  Piety, Guardian of Riddles
651          651  Lirtilsa72   24   Male      132                  Persuasion

     Price
320   4.00
651   3.33
('Lirtim36', 15, 'Other / Non-Disclosed')
     Purchase ID        SN  Age                 Gender  Item ID  \
401          401  Lirtim36   15  Other / Non-Disclosed       46

                   Item Name  Price
401  Hopeless Ebon Dualblade   1.33
('Lirtimst73', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID                 Item Name  \
160          160  Lirtimst73   24   Male       44     Bonecarvin Battle Axe
525          525  Lirtimst73   24   Male      126  Exiled Mithril Longsword

     Price
160   2.38
525   2.00
('Lirtirra37', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID           Item Name  Price
265          265  Lirtirra37   25   Male      172  Blade of the Grave   3.14
('Lirtirra81', 12, 'Male')
     Purchase ID          SN  Age Gender  Item ID          Item Name  Price
531          531  Lirtirra81   12   Male      143  Frenzied Scimitar   1.56
('Lirtistanya48', 24, 'Male')
     Purchase ID             SN  Age Gender  Item ID     Item Name  Price
475          475  Lirtistanya48   24   Male        6   Rusty Skull    3.7
691          691  Lirtistanya48   24   Male      112  Worldbreaker    2.6
('Lirtosia63', 34, 'Male')
     Purchase ID          SN  Age Gender  Item ID   Item Name  Price
77            77  Lirtosia63   34   Male       20  Netherbane   3.27
770          770  Lirtosia63   34   Male       12       Dawne   1.02
('Lirtossa60', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
244          244  Lirtossa60   24   Male       37
682          682  Lirtossa60   24   Male      135

                               Item Name  Price
244  Shadow Strike, Glory of Ending Hope   3.16
682              Warped Diamond Crusader   1.40
('Lirtossa84', 11, 'Male')
     Purchase ID          SN  Age Gender  Item ID         Item Name  Price
26            26  Lirtossa84   11   Male       71            Demise   1.61
299          299  Lirtossa84   11   Male      164  Exiled Doomblade   1.63
('Lisadar44', 27, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
190          190  Lisadar44   27   Male       69

                           Item Name  Price
190  Frenzy, Defender of the Harvest   1.98
('Lisasi93', 13, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
139          139  Lisasi93   13   Male      158
292          292  Lisasi93   13   Male       70

                              Item Name  Price
139  Darkheart, Butcher of the Champion   2.45
292                          Hope's End   1.03
('Lisassa64', 21, 'Female')
    Purchase ID         SN  Age  Gender  Item ID                    Item Name  \
15           15  Lisassa64   21  Female       98  Deadline, Voice Of Subtlety

    Price
15   2.89
('Lisassala98', 16, 'Male')
    Purchase ID           SN  Age Gender  Item ID                 Item Name  \
96           96  Lisassala98   16   Male       56  Foul Titanium Battle Axe

    Price
96   2.92
('Lisassasda39', 36, 'Male')
     Purchase ID            SN  Age Gender  Item ID Item Name  Price
659          659  Lisassasda39   36   Male      140   Striker   2.94
('Lisassasta50', 25, 'Male')
     Purchase ID            SN  Age Gender  Item ID               Item Name  \
724          724  Lisassasta50   25   Male      144  Blood Infused Guardian

     Price
724   1.94
('Lisast87', 19, 'Male')
     Purchase ID        SN  Age Gender  Item ID                Item Name  \
129          129  Lisast87   19   Male       74         Yearning Crusher
709          709  Lisast87   19   Male       75  Brutality Ivory Warmace

     Price
129   4.18
709   2.42
('Lisast98', 22, 'Male')
     Purchase ID        SN  Age Gender  Item ID    Item Name  Price
592          592  Lisast98   22   Male      170  Shadowsteel   3.97
('Lisico81', 10, 'Male')
     Purchase ID        SN  Age Gender  Item ID     Item Name  Price
411          411  Lisico81   10   Male      101  Final Critic   4.19
('Lisilsa62', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID     Item Name  Price
712          712  Lisilsa62   25   Male       92  Final Critic   4.88
('Lisim51', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID        Item Name  Price
527          527  Lisim51   24   Male      102          Avenger   3.44
604          604  Lisim51   24   Male       34  Retribution Axe   2.22
('Lisim78', 20, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
0              0  Lisim78   20   Male      108
67            67  Lisim78   20   Male      138
245          245  Lisim78   20   Male       85

                                     Item Name  Price
0    Extraction, Quickblade Of Trembling Hands   3.53
67              Peacekeeper, Wit of Dark Magic   4.74
245                             Malificent Bag   1.75
('Lisiriya82', 32, 'Male')
     Purchase ID          SN  Age Gender  Item ID          Item Name  Price
412          412  Lisiriya82   32   Male       86  Stormfury Lantern   2.27
('Lisirra25', 20, 'Male')
    Purchase ID         SN  Age Gender  Item ID      Item Name  Price
16           16  Lisirra25   20   Male       40  Second Chance   2.52
('Lisirra58', 20, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
641          641  Lisirra58   20  Female       49

                            Item Name  Price
641  The Oculus, Token of Lost Worlds   2.96
('Lisirra87', 29, 'Male')
    Purchase ID         SN  Age Gender  Item ID  \
25           25  Lisirra87   29   Male      178

                                       Item Name  Price
25  Oathbreaker, Last Hope of the Breaking Storm   4.23
('Lisista27', 16, 'Male')
     Purchase ID         SN  Age Gender  Item ID        Item Name  Price
122          122  Lisista27   16   Male      174  Primitive Blade   3.47
('Lisista54', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
238          238  Lisista54   21   Male       42
723          723  Lisista54   21   Male      177

                                    Item Name  Price
238                           The Decapitator   1.75
723  Winterthorn, Defender of Shifting Worlds   2.08
('Lisista63', 17, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
328          328  Lisista63   17   Male      152  Darkheart   1.74
('Lisjaskan36', 11, 'Male')
     Purchase ID           SN  Age Gender  Item ID    Item Name  Price
751          751  Lisjaskan36   11   Male      180  Stormcaller   3.36
('Lisjaskya84', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
192          192  Lisjaskya84   25   Male       98

                       Item Name  Price
192  Deadline, Voice Of Subtlety   2.89
('Lisopela58', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
170          170  Lisopela58   22   Male       75
293          293  Lisopela58   22   Male      117
472          472  Lisopela58   22   Male       18

                             Item Name  Price
170            Brutality Ivory Warmace   2.42
293  Heartstriker, Legacy of the Light   1.79
472         Torchlight, Bond of Storms   4.65
('Lisosia66', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID  Item Name  Price
334          334  Lisosia66   21   Male       11  Brimstone   3.65
('Lisosia93', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
74            74  Lisosia93   25   Male       89
120          120  Lisosia93   25   Male       24
224          224  Lisosia93   25   Male      157
603          603  Lisosia93   25   Male      141
609          609  Lisosia93   25   Male       40

                             Item Name  Price
74   Blazefury, Protector of Delusions   4.64
120                      Warped Fetish   3.81
224            Spada, Etcher of Hatred   4.80
603                         Persuasion   3.19
609                      Second Chance   2.52
('Lisossa25', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
338          338  Lisossa25   22   Male       13
710          710  Lisossa25   22   Male       99

                                Item Name  Price
338                              Serenity   1.41
710  Expiration, Warscythe Of Lost Worlds   1.71
('Lisossa46', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID        Item Name  Price
326          326  Lisossa46   25   Male       54  Eternal Cleaver    2.5
('Lisossala30', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID       Item Name  Price
455          455  Lisossala30   20   Male      103  Singed Scalpel   4.35
('Lisossanya98', 37, 'Male')
     Purchase ID            SN  Age Gender  Item ID Item Name  Price
127          127  Lisossanya98   37   Male      102   Avenger   3.44
('Lisotesta51', 15, 'Female')
     Purchase ID           SN  Age  Gender  Item ID               Item Name  \
409          409  Lisotesta51   15  Female      144  Blood Infused Guardian

     Price
409   1.94
('Lisovynya38', 40, 'Male')
   Purchase ID           SN  Age Gender  Item ID          Item Name  Price
1            1  Lisovynya38   40   Male      143  Frenzied Scimitar   1.56
('Malarrian73', 18, 'Male')
     Purchase ID           SN  Age Gender  Item ID                Item Name  \
547          547  Malarrian73   18   Male      135  Warped Diamond Crusader

     Price
547    1.4
('Malil90', 22, 'Male')
     Purchase ID       SN  Age Gender  Item ID                  Item Name  \
362          362  Malil90   22   Male      107  Splitter, Foe Of Subtlety

     Price
362   2.18
('Malon70', 23, 'Male')
     Purchase ID       SN  Age Gender  Item ID              Item Name  Price
488          488  Malon70   23   Male       44  Bonecarvin Battle Axe   2.38
('Maluncil97', 25, 'Other / Non-Disclosed')
     Purchase ID          SN  Age                 Gender  Item ID  \
549          549  Maluncil97   25  Other / Non-Disclosed      146
629          629  Maluncil97   25  Other / Non-Disclosed      107

                     Item Name  Price
549       Warped Iron Scimitar   3.10
629  Splitter, Foe Of Subtlety   2.18
('Malunil62', 18, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
188          188  Malunil62   18   Male       88
725          725  Malunil62   18   Male       72

                            Item Name  Price
188  Emberling, Defender of Delusions   3.75
725                     Winter's Bite   3.77
('Maradaran90', 35, 'Female')
     Purchase ID           SN  Age  Gender  Item ID  \
196          196  Maradaran90   35  Female        9

                             Item Name  Price
196  Thorn, Conqueror of the Corrupted   2.73
('Maradarnya40', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
707          707  Maradarnya40   20   Male       38

                             Item Name  Price
707  The Void, Vengeance of Dark Magic   2.37
('Marassa62', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID       Item Name  Price
476          476  Marassa62   21   Male      103  Singed Scalpel   4.35
('Marast30', 18, 'Female')
     Purchase ID        SN  Age  Gender  Item ID  \
157          157  Marast30   18  Female      108

                                     Item Name  Price
157  Extraction, Quickblade Of Trembling Hands   3.53
('Maridisya31', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
130          130  Maridisya31   25   Male      120    Agatha   3.08
('Marilsa69', 25, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
72            72  Marilsa69   25  Female      178
579          579  Marilsa69   25  Female       12

                                        Item Name  Price
72   Oathbreaker, Last Hope of the Breaking Storm   4.23
579                                         Dawne   1.02
('Marilsanya48', 25, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
151          151  Marilsanya48   25   Male      105

                        Item Name  Price
151  Hailstorm Shadowsteel Scythe   3.03
('Marilsasya33', 19, 'Male')
     Purchase ID            SN  Age Gender  Item ID          Item Name  Price
399          399  Marilsasya33   19   Male      143  Frenzied Scimitar   1.56
452          452  Marilsasya33   19   Male       32            Orenmir   1.14
('Marim28', 25, 'Female')
     Purchase ID       SN  Age  Gender  Item ID                   Item Name  \
289          289  Marim28   25  Female       83                  Lifebender
418          418  Marim28   25  Female      125  Whistling Mithril Warblade

     Price
289   3.33
418   1.00
('Marirrasta50', 16, 'Male')
     Purchase ID            SN  Age Gender  Item ID   Item Name  Price
181          181  Marirrasta50   16   Male       51  Endbringer   4.66
('Marjask87', 20, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
152          152  Marjask87   20   Male      110  Suspension   1.44
('Marokian45', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
414          414  Marokian45   23   Male      108

                                     Item Name  Price
414  Extraction, Quickblade Of Trembling Hands   3.53
('Maropast28', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
102          102  Maropast28   24   Male      109

                            Item Name  Price
102  Downfall, Scalpel Of The Emperor   4.76
('Marughi89', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
491          491  Marughi89   22   Male       22   Amnesia   2.18
('Marundi65', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
737          737  Marundi65   22   Male      149

                             Item Name  Price
737  Tranquility, Razor of Black Magic   1.75
('Marynde90', 30, 'Male')
     Purchase ID         SN  Age Gender  Item ID                Item Name  \
562          562  Marynde90   30   Male       83               Lifebender
624          624  Marynde90   30   Male       29  Chaos, Ender of the End

     Price
562   3.33
624   1.98
('Meosridil82', 18, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
522          522  Meosridil82   18   Male       82   Nirvana    4.9
('Mindadaran26', 13, 'Female')
    Purchase ID            SN  Age  Gender  Item ID  \
76           76  Mindadaran26   13  Female       88

                           Item Name  Price
76  Emberling, Defender of Delusions   3.75
('Mindesi74', 22, 'Male')
     Purchase ID         SN  Age Gender  Item ID            Item Name  Price
669          669  Mindesi74   22   Male       45  Glinting Glass Edge   3.85
694          694  Mindesi74   22   Male      164     Exiled Doomblade   1.63
('Mindetosya30', 24, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
197          197  Mindetosya30   24   Male       37

                               Item Name  Price
197  Shadow Strike, Glory of Ending Hope   3.16
('Mindilsa34', 24, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
306          306  Mindilsa34   24  Female       38

                             Item Name  Price
306  The Void, Vengeance of Dark Magic   2.37
('Mindilsa60', 21, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
662          662  Mindilsa60   21   Male        0  Splinter   1.28
('Mindimnya67', 23, 'Male')
     Purchase ID           SN  Age Gender  Item ID                Item Name  \
646          646  Mindimnya67   23   Male      116  Renewed Skeletal Katana

     Price
646   4.18
('Mindirranya33', 35, 'Male')
     Purchase ID             SN  Age Gender  Item ID Item Name  Price

739          739  Mindirranya33   35   Male       61  Ragnarok   3.87
('Mindista32', 24, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
179          179  Mindista32   24   Male       59

                         Item Name  Price
179  Lightning, Etcher of the King   4.23
('Mindjasksya61', 17, 'Male')
     Purchase ID             SN  Age Gender  Item ID     Item Name  Price
752          752  Mindjasksya61   17   Male      112  Worldbreaker    2.6
('Mindossa76', 41, 'Male')
     Purchase ID          SN  Age Gender  Item ID            Item Name  Price
477          477  Mindossa76   41   Male      173  Stormfury Longsword   4.93
('Minduli80', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
298          298  Minduli80   25   Male      110  Suspension   1.44
('Minduri31', 39, 'Male')
     Purchase ID         SN  Age Gender  Item ID          Item Name  Price
195          195  Minduri31   39   Male      113  Solitude's Reaver   4.07
('Nitherian58', 28, 'Male')
     Purchase ID           SN  Age Gender  Item ID          Item Name  Price
115          115  Nitherian58   28   Male       13           Serenity   1.41
606          606  Nitherian58   28   Male      123  Twilight's Carver   2.28
('Palatyon26', 21, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
342          342  Palatyon26   21   Male       38

                             Item Name  Price
342  The Void, Vengeance of Dark Magic   2.37
('Palyon91', 21, 'Male')
    Purchase ID        SN  Age Gender  Item ID  Item Name  Price
57           57  Palyon91   21   Male       80  Dreamsong   3.39
('Peorith44', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
230          230  Peorith44   24   Male      102   Avenger   3.44
('Phaedasurap84', 17, 'Male')
     Purchase ID             SN  Age Gender  Item ID           Item Name  \
645          645  Phaedasurap84   17   Male      114  Yearning Mageblade

     Price
645   3.82
('Phaedue89', 22, 'Female')
     Purchase ID         SN  Age  Gender  Item ID            Item Name  Price
336          336  Phaedue89   22  Female       45  Glinting Glass Edge   3.85
('Phaelap26', 25, 'Female')
     Purchase ID         SN  Age  Gender  Item ID   Item Name  Price
55            55  Phaelap26   25  Female       84  Arcane Gem   3.79
445          445  Phaelap26   25  Female      150   Deathraze   2.85
('Phaena87', 20, 'Male')
     Purchase ID        SN  Age Gender  Item ID                 Item Name  \
64            64  Phaena87   20   Male       56  Foul Titanium Battle Axe
133          133  Phaena87   20   Male        0                  Splinter
456          456  Phaena87   20   Male      124            Venom Claymore

     Price
64    2.92
133   1.28
456   1.29
('Phaestycal84', 23, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
581          581  Phaestycal84   23   Male      117
684          684  Phaestycal84   23   Male      169

                                  Item Name  Price
581       Heartstriker, Legacy of the Light   1.79
684  Interrogator, Blood Blade of the Queen   2.18
('Pheodai94', 29, 'Male')
    Purchase ID         SN  Age Gender  Item ID          Item Name  Price
70           70  Pheodai94   29   Male      143  Frenzied Scimitar   1.56
('Pheodaisun84', 30, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
100          100  Pheodaisun84   30   Male       12
118          118  Pheodaisun84   30   Male       78
417          417  Pheodaisun84   30   Male       98

                       Item Name  Price
100                        Dawne   1.02
118   Glimmer, Ender of the Moon   4.40
417  Deadline, Voice Of Subtlety   2.89
('Pheosrinudeu70', 20, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
356          356  Pheosrinudeu70   20   Male      138
652          652  Pheosrinudeu70   20   Male       75

                          Item Name  Price
356  Peacekeeper, Wit of Dark Magic   4.74
652         Brutality Ivory Warmace   2.42
('Pheosurllorin41', 23, 'Female')
     Purchase ID               SN  Age  Gender  Item ID  \
555          555  Pheosurllorin41   23  Female        7
754          754  Pheosurllorin41   23  Female       79

                        Item Name  Price
555  Thorn, Satchel of Dark Souls   1.33
754           Alpha, Oath of Zeal   4.05
('Pheulidil31', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID    Item Name  Price
500          500  Pheulidil31   20   Male      100  Blindscythe   3.27
('Pheusrical25', 23, 'Male')
     Purchase ID            SN  Age Gender  Item ID           Item Name  Price
200          200  Pheusrical25   23   Male      114  Yearning Mageblade   3.82
('Pheutherin27', 24, 'Male')
     Purchase ID            SN  Age Gender  Item ID         Item Name  Price
358          358  Pheutherin27   24   Male       74  Yearning Crusher   4.18
('Phiallylis33', 19, 'Male')
     Purchase ID            SN  Age Gender  Item ID             Item Name  \
741          741  Phiallylis33   19   Male      145  Fiery Glass Crusader

     Price
741   4.58
('Phiarithdeu40', 20, 'Male')
    Purchase ID             SN  Age Gender  Item ID  \
21           21  Phiarithdeu40   20   Male      168

                              Item Name  Price
21  Sun Strike, Jaws of Twisted Visions   1.48
('Philodil43', 33, 'Male')
    Purchase ID          SN  Age Gender  Item ID       Item Name  Price
75           75  Philodil43   33   Male      124  Venom Claymore   1.29
('Phiristi62', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
701          701  Phiristi62   25   Male       10  Sleepwalker   1.79
('Phistym51', 37, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
202          202  Phistym51   37   Male       82   Nirvana    4.9
521          521  Phistym51   37   Male       50      Dawn    4.6
('Phistyn52', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID         Item Name  Price
382          382  Phistyn52   24   Male      164  Exiled Doomblade   1.63
('Phyali88', 15, 'Female')
     Purchase ID        SN  Age  Gender  Item ID     Item Name  Price
113          113  Phyali88   15  Female      140       Striker   2.94
134          134  Phyali88   15  Female        2       Verdict   2.48
273          273  Phyali88   15  Female       92  Final Critic   4.88
('Poshilsa82', 16, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
571          571  Poshilsa82   16   Male      165

                       Item Name  Price
571  Bone Crushing Silver Skewer   4.86
('Qarirwen82', 33, 'Male')
    Purchase ID          SN  Age Gender  Item ID  \
86           86  Qarirwen82   33   Male      129

                             Item Name  Price
86  Fate, Vengeance of Eternal Justice   1.54
('Qilalista41', 23, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
344          344  Qilalista41   23   Male       19

                         Item Name  Price
344  Pursuit, Cudgel of Necromancy   1.02
('Qilanrion65', 37, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
208          208  Qilanrion65   37   Male      105

                        Item Name  Price
208  Hailstorm Shadowsteel Scythe   3.03
('Qilatista90', 17, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
149          149  Qilatista90   17   Male      161    Devine   1.76
('Qilunan34', 23, 'Male')
     Purchase ID         SN  Age Gender  Item ID             Item Name  Price
438          438  Qilunan34   23   Male      145  Fiery Glass Crusader   4.58
('Quaecjask96', 9, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
692          692  Quaecjask96    9   Male       78

                      Item Name  Price
692  Glimmer, Ender of the Moon    4.4
('Quanenrian83', 15, 'Male')
     Purchase ID            SN  Age Gender  Item ID              Item Name  \
619          619  Quanenrian83   15   Male       55  Vindictive Glass Edge

     Price
619   2.27
('Quanrion96', 21, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
613          613  Quanrion96   21  Female      159

                             Item Name  Price
613  Oathbreaker, Spellblade of Trials   3.08
('Quanunwen42', 23, 'Female')
     Purchase ID           SN  Age  Gender  Item ID       Item Name  Price
254          254  Quanunwen42   23  Female       94  Mourning Blade   3.49
('Quaranmol58', 24, 'Male')
     Purchase ID           SN  Age Gender  Item ID   Item Name  Price
243          243  Quaranmol58   24   Male       83  Lifebender   3.33
('Quarrion42', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
439          439  Quarrion42   22   Male       59

                         Item Name  Price
439  Lightning, Etcher of the King   4.23
('Quilassa66', 7, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
658          658  Quilassa66    7  Female      178

                                        Item Name  Price
658  Oathbreaker, Last Hope of the Breaking Storm   4.23
('Quinarap53', 15, 'Male')
     Purchase ID          SN  Age Gender  Item ID                Item Name  \
389          389  Quinarap53   15   Male      157  Spada, Etcher of Hatred
597          597  Quinarap53   15   Male       86        Stormfury Lantern

     Price
389   4.80
597   2.27
('Raesty92', 12, 'Male')
     Purchase ID        SN  Age Gender  Item ID  \
56            56  Raesty92   12   Male      108
408          408  Raesty92   12   Male       53
755          755  Raesty92   12   Male       76

                                     Item Name  Price
56   Extraction, Quickblade Of Trembling Hands   3.53
408                          Vengeance Cleaver   2.05
755                   Haunted Bronzed Bludgeon   3.15
('Raillydeu47', 14, 'Male')
     Purchase ID           SN  Age Gender  Item ID                 Item Name  \
487          487  Raillydeu47   14   Male       93  Apocalyptic Battlescythe

     Price
487   1.97
('Rairin89', 24, 'Male')
     Purchase ID        SN  Age Gender  Item ID             Item Name  Price
235          235  Rairin89   24   Male      163  Thunderfury Scimitar   3.45
('Rairith81', 15, 'Other / Non-Disclosed')
     Purchase ID         SN  Age                 Gender  Item ID  \
350          350  Rairith81   15  Other / Non-Disclosed       34

           Item Name  Price
350  Retribution Axe   2.22
('Raisty38', 15, 'Male')
     Purchase ID        SN  Age Gender  Item ID   Item Name  Price
425          425  Raisty38   15   Male       20  Netherbane   3.27
('Rarallo90', 33, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
138          138  Rarallo90   33   Male      136
319          319  Rarallo90   33   Male      144
678          678  Rarallo90   33   Male      108

                                     Item Name  Price
138               Ghastly Adamantite Protector   3.58
319                     Blood Infused Guardian   1.94
678  Extraction, Quickblade Of Trembling Hands   3.53
('Rastynusuir31', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID              Item Name  \
748          748  Rastynusuir31   20   Male       55  Vindictive Glass Edge

     Price
748   2.27
('Raysistast71', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID  Item Name  Price
377          377  Raysistast71   20   Male       11  Brimstone   3.65
('Reulae52', 10, 'Female')
    Purchase ID        SN  Age  Gender  Item ID                Item Name  \
38           38  Reulae52   10  Female      116  Renewed Skeletal Katana

    Price
38   4.18
('Reunasu60', 22, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
18            18  Reunasu60   22  Female       82
740          740  Reunasu60   22  Female      127

                        Item Name  Price
18                        Nirvana   4.90
740  Heartseeker, Reaver of Souls   3.92
('Rianistast50', 22, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
464          464  Rianistast50   22   Male      178

                                        Item Name  Price
464  Oathbreaker, Last Hope of the Breaking Storm   4.23
('Rilaera56', 20, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
287          287  Rilaera56   20   Male        5  Putrid Fan   4.08
('Ririp86', 25, 'Male')
     Purchase ID       SN  Age Gender  Item ID                Item Name  Price
110          110  Ririp86   25   Male      139  Mercy, Katana of Dismay   4.94
('Risty84', 25, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
380          380  Risty84   25   Male       50      Dawn    4.6
('Ristydru66', 27, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
193          193  Ristydru66   27   Male       62  Piece Maker   1.87
('Rithe53', 15, 'Female')
     Purchase ID       SN  Age  Gender  Item ID  Item Name  Price
607          607  Rithe53   15  Female       80  Dreamsong   3.39
('Ryanara76', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID        Item Name  Price
353          353  Ryanara76   25   Male      174  Primitive Blade   3.47
('Saedaiphos46', 18, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
322          322  Saedaiphos46   18   Male       37
346          346  Saedaiphos46   18   Male      121
764          764  Saedaiphos46   18   Male      113

                               Item Name  Price
322  Shadow Strike, Glory of Ending Hope   3.16
346                             Massacre   1.60
764                    Solitude's Reaver   4.07
('Saelaephos52', 21, 'Male')
    Purchase ID            SN  Age Gender  Item ID                Item Name  \
12           12  Saelaephos52   21   Male      116  Renewed Skeletal Katana
50           50  Saelaephos52   21   Male       22                  Amnesia

    Price
12   4.18
50   2.18
('Saena74', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID              Item Name  Price
180          180  Saena74   24   Male       95  Singed Onyx Warscythe   4.74
('Saena89', 23, 'Male')
     Purchase ID       SN  Age Gender  Item ID            Item Name  Price
716          716  Saena89   23   Male      106  Crying Steel Sickle   3.41
('Saerallora71', 23, 'Male')
     Purchase ID            SN  Age Gender  Item ID                 Item Name  \
250          250  Saerallora71   23   Male       87  Deluge, Edge of the West

     Price
250   4.43
('Saesrideu94', 35, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
14            14  Saesrideu94   35   Male      165
264          264  Saesrideu94   35   Male      119

                                     Item Name  Price
14                 Bone Crushing Silver Skewer   4.86
264  Stormbringer, Dark Blade of Ending Misery   4.32
('Saida58', 16, 'Male')
     Purchase ID       SN  Age Gender  Item ID   Item Name  Price
260          260  Saida58   16   Male       70  Hope's End   1.03
('Saisrilis27', 16, 'Male')
     Purchase ID           SN  Age Gender  Item ID       Item Name  Price
374          374  Saisrilis27   16   Male       85  Malificent Bag   1.75
('Saistyphos30', 35, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
372          372  Saistyphos30   35   Male       64
483          483  Saistyphos30   35   Male      108
688          688  Saistyphos30   35   Male       29

                                     Item Name  Price
372                              Fusion Pummel   4.82
483  Extraction, Quickblade Of Trembling Hands   3.53
688                    Chaos, Ender of the End   1.98
('Salilis27', 40, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
480          480  Salilis27   40   Male       59

                         Item Name  Price
480  Lightning, Etcher of the King   4.23
('Sally64', 25, 'Female')
     Purchase ID       SN  Age  Gender  Item ID                Item Name  \
524          524  Sally64   25  Female       46  Hopeless Ebon Dualblade

     Price
524   1.33
('Sastydeu50', 35, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
512          512  Sastydeu50   35   Male      169

                                  Item Name  Price
512  Interrogator, Blood Blade of the Queen   2.18
('Sausosia74', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
415          415  Sausosia74   22   Male      120
640          640  Sausosia74   22   Male      108

                                     Item Name  Price
415                                     Agatha   3.08
640  Extraction, Quickblade Of Trembling Hands   3.53
('Seolollo93', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID            Item Name  Price
589          589  Seolollo93   30   Male      106  Crying Steel Sickle   3.41
('Seosrim97', 20, 'Male')
     Purchase ID         SN  Age Gender  Item ID                  Item Name  \
602          602  Seosrim97   20   Male       65  Conqueror Adamantite Mace
621          621  Seosrim97   20   Male       26                Unholy Wand

     Price
602   4.24
621   1.12
('Seudaillorap38', 27, 'Male')
     Purchase ID              SN  Age Gender  Item ID             Item Name  \
123          123  Seudaillorap38   27   Male       81             Dreamkiss
596          596  Seudaillorap38   27   Male      146  Warped Iron Scimitar

     Price
123   3.61
596   3.10
('Seuthep89', 8, 'Male')
    Purchase ID         SN  Age Gender  Item ID    Item Name  Price
37           37  Seuthep89    8   Male       73  Ritual Mace   2.05
('Shaidanu32', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
212          212  Shaidanu32   23   Male      159

                             Item Name  Price
212  Oathbreaker, Spellblade of Trials   3.08
('Shidai42', 29, 'Male')
     Purchase ID        SN  Age Gender  Item ID                     Item Name  \
540          540  Shidai42   29   Male        7  Thorn, Satchel of Dark Souls

     Price
540   1.33
('Siala43', 30, 'Male')

     Purchase ID       SN  Age Gender  Item ID          Item Name  Price
24            24  Siala43   30   Male      141         Persuasion   3.19
266          266  Siala43   30   Male      113  Solitude's Reaver   4.07
('Siallylis44', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
302          302  Siallylis44   20   Male        4
305          305  Siallylis44   20   Male      179
536          536  Siallylis44   20   Male      101

                           Item Name  Price
302               Bloodlord's Fetish   1.70
305  Wolf, Promise of the Moonwalker   4.48
536                     Final Critic   4.19
('Siana77', 12, 'Male')
     Purchase ID       SN  Age Gender  Item ID                 Item Name  \
413          413  Siana77   12   Male       93  Apocalyptic Battlescythe

     Price
413   1.97
('Siarithria38', 38, 'Other / Non-Disclosed')
     Purchase ID            SN  Age                 Gender  Item ID  \
22            22  Siarithria38   38  Other / Non-Disclosed       24
747          747  Siarithria38   38  Other / Non-Disclosed      146

                Item Name  Price
22          Warped Fetish   3.81
747  Warped Iron Scimitar   3.10
('Sida61', 20, 'Female')
     Purchase ID      SN  Age  Gender  Item ID      Item Name  Price
392          392  Sida61   20  Female      181  Reaper's Toll   1.66
615          615  Sida61   20  Female       72  Winter's Bite   3.77
('Sidap51', 11, 'Male')
     Purchase ID       SN  Age Gender  Item ID                  Item Name  \
163          163  Sidap51   11   Male       65  Conqueror Adamantite Mace

     Price
163   4.24
('Silaera56', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
529          529  Silaera56   21   Male      142
612          612  Silaera56   21   Male       52
657          657  Silaera56   21   Male       19

                         Item Name  Price
529                Righteous Might   2.62
612                         Hatred   4.84
657  Pursuit, Cudgel of Necromancy   1.02
('Siralsudeu54', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
396          396  Siralsudeu54   20   Male      131
535          535  Siralsudeu54   20   Male      155

                     Item Name  Price
396                       Fury   1.44
535  War-Forged Gold Deflector   1.01
('Sisur91', 7, 'Male')
     Purchase ID       SN  Age Gender  Item ID     Item Name  Price
778          778  Sisur91    7   Male      101  Final Critic   4.19
('Smaistysu35', 30, 'Male')
     Purchase ID           SN  Age Gender  Item ID            Item Name  Price
275          275  Smaistysu35   30   Male      173  Stormfury Longsword   4.93
650          650  Smaistysu35   30   Male      161               Devine   1.76
('Sondadar26', 9, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
546          546  Sondadar26    9   Male      159
575          575  Sondadar26    9   Male      137

                             Item Name  Price
546  Oathbreaker, Spellblade of Trials   3.08
575     Aetherius, Boon of the Blessed   3.39
('Sondadarya58', 19, 'Male')
     Purchase ID            SN  Age Gender  Item ID       Item Name  Price
108          108  Sondadarya58   19   Male       85  Malificent Bag   1.75
('Sondassan80', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID     Item Name  Price
537          537  Sondassan80   25   Male      112  Worldbreaker    2.6
('Sondassasya91', 21, 'Female')
     Purchase ID             SN  Age  Gender  Item ID      Item Name  Price
444          444  Sondassasya91   21  Female       24  Warped Fetish   3.81
('Sondastsda82', 24, 'Male')
     Purchase ID            SN  Age Gender  Item ID             Item Name  \
207          207  Sondastsda82   24   Male      145  Fiery Glass Crusader
255          255  Sondastsda82   24   Male       71                Demise
465          465  Sondastsda82   24   Male        4    Bloodlord's Fetish

     Price
207   4.58
255   1.61
465   1.70
('Sondilsaya62', 21, 'Male')
    Purchase ID            SN  Age Gender  Item ID           Item Name  Price
39           39  Sondilsaya62   21   Male      172  Blade of the Grave   3.14
('Sondim68', 22, 'Female')
     Purchase ID        SN  Age  Gender  Item ID                 Item Name  \
166          166  Sondim68   22  Female       30               Stormcaller
478          478  Sondim68   22  Female       35  Heartless Bone Dualblade

     Price
166   2.21
478   3.45
('Sondim73', 19, 'Male')
    Purchase ID        SN  Age Gender  Item ID   Item Name  Price
34           34  Sondim73   19   Male      160  Azurewrath    4.4
('Sondimla25', 19, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
281          281  Sondimla25   19   Male       68

                             Item Name  Price
281  Storm-Weaver, Slayer of Inception   4.32
('Sondistanya61', 18, 'Female')
     Purchase ID             SN  Age  Gender  Item ID  \
450          450  Sondistanya61   18  Female       35

                    Item Name  Price
450  Heartless Bone Dualblade   3.45
('Sondossa69', 7, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
481          481  Sondossa69    7   Male      179

                           Item Name  Price
481  Wolf, Promise of the Moonwalker   4.48
('Strithenu87', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
312          312  Strithenu87   20   Male      147
410          410  Strithenu87   20   Male       99
661          661  Strithenu87   20   Male       60

                                Item Name  Price
312     Hellreaver, Heirloom of Inception   4.93
410  Expiration, Warscythe Of Lost Worlds   1.71
661                                  Wolf   3.54
('Styaduen40', 17, 'Male')
     Purchase ID          SN  Age Gender  Item ID      Item Name  Price
162          162  Styaduen40   17   Male      181  Reaper's Toll   1.66
('Sundadar27', 31, 'Male')
     Purchase ID          SN  Age Gender  Item ID           Item Name  Price
158          158  Sundadar27   31   Male      111        Misery's End   4.89
232          232  Sundadar27   31   Male      114  Yearning Mageblade   3.82
('Sundadarla27', 23, 'Male')
     Purchase ID            SN  Age Gender  Item ID         Item Name  Price
471          471  Sundadarla27   23   Male      122  Unending Tyranny   2.85
('Sundassa93', 16, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
719          719  Sundassa93   16   Male      158

                              Item Name  Price
719  Darkheart, Butcher of the Champion   2.45
('Sundim98', 21, 'Other / Non-Disclosed')
     Purchase ID        SN  Age                 Gender  Item ID Item Name  \
111          111  Sundim98   21  Other / Non-Disclosed       41     Orbit

     Price
111   4.75
('Sundirrala66', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
249          249  Sundirrala66   20   Male       16
349          349  Sundirrala66   20   Male       59

                         Item Name  Price
249                Restored Bauble   3.55
349  Lightning, Etcher of the King   4.23
('Sundista37', 26, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
573          573  Sundista37   26   Male      156

                        Item Name  Price
573  Soul-Forged Steel Shortsword   1.77
('Sundjask71', 32, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
482          482  Sundjask71   32  Female       77

                      Item Name  Price
482  Piety, Guardian of Riddles    4.0
('Syally44', 17, 'Male')
     Purchase ID        SN  Age Gender  Item ID          Item Name  Price
542          542  Syally44   17   Male       22            Amnesia   2.18
568          568  Syally44   17   Male      123  Twilight's Carver   2.28
('Syalollorap93', 22, 'Female')
     Purchase ID             SN  Age  Gender  Item ID  \
296          296  Syalollorap93   22  Female       65

                     Item Name  Price
296  Conqueror Adamantite Mace   4.24
('Syathe73', 30, 'Female')
     Purchase ID        SN  Age  Gender  Item ID                Item Name  \
177          177  Syathe73   30  Female      135  Warped Diamond Crusader

     Price
177    1.4
('Syathecal44', 16, 'Male')
     Purchase ID           SN  Age Gender  Item ID                Item Name  \
626          626  Syathecal44   16   Male       75  Brutality Ivory Warmace

     Price
626   2.42
('Taeduenu92', 19, 'Female')
     Purchase ID          SN  Age  Gender  Item ID           Item Name  Price
233          233  Taeduenu92   19  Female       66  Victor Iron Spikes    4.4
('Thourdirra92', 19, 'Male')
     Purchase ID            SN  Age Gender  Item ID   Item Name  Price
505          505  Thourdirra92   19   Male      110  Suspension   1.44
('Thrientossa55', 20, 'Male')
     Purchase ID             SN  Age Gender  Item ID  Item Name  Price
185          185  Thrientossa55   20   Male      150  Deathraze   2.85
('Thryallym62', 24, 'Male')
     Purchase ID           SN  Age Gender  Item ID          Item Name  Price
104          104  Thryallym62   24   Male       53  Vengeance Cleaver   2.05
('Tyaedainu44', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID  Item Name  Price
365          365  Tyaedainu44   25   Male       43  Foul Edge   3.54
('Tyaelaelis94', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID  \
616          616  Tyaelaelis94   20   Male       78

                      Item Name  Price
616  Glimmer, Ender of the Moon    4.4
('Tyaelistidru84', 19, 'Female')
     Purchase ID              SN  Age  Gender  Item ID Item Name  Price
697          697  Tyaelistidru84   19  Female        1  Crucifer   3.26
('Tyaelly53', 17, 'Female')
     Purchase ID         SN  Age  Gender  Item ID Item Name  Price
699          699  Tyaelly53   17  Female      130     Alpha   2.07
('Tyaelo67', 39, 'Male')
     Purchase ID        SN  Age Gender  Item ID     Item Name  Price
252          252  Tyaelo67   39   Male       92  Final Critic   4.88
('Tyaelorap29', 25, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
159          159  Tyaelorap29   25   Male       39
759          759  Tyaelorap29   25   Male       72

                                Item Name  Price
159  Betrayal, Whisper of Grieving Widows   3.94
759                         Winter's Bite   3.77
('Tyaenasti87', 24, 'Female')
     Purchase ID           SN  Age  Gender  Item ID     Item Name  Price
225          225  Tyaenasti87   24  Female      154  Feral Katana    4.4
('Tyaerith73', 36, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
107          107  Tyaerith73   36   Male       99

                                Item Name  Price
107  Expiration, Warscythe Of Lost Worlds   1.71
('Tyalaesu89', 25, 'Male')
     Purchase ID          SN  Age Gender  Item ID             Item Name  Price
316          316  Tyalaesu89   25   Male       15  Soul Infused Crystal   2.96
('Tyananurgue44', 18, 'Male')
     Purchase ID             SN  Age Gender  Item ID    Item Name  Price
379          379  Tyananurgue44   18   Male      100  Blindscythe   3.27
('Tyarithn67', 27, 'Male')
     Purchase ID          SN  Age Gender  Item ID Item Name  Price
677          677  Tyarithn67   27   Male       32   Orenmir   1.14
('Tyeoralru41', 15, 'Male')
     Purchase ID           SN  Age Gender  Item ID Item Name  Price
355          355  Tyeoralru41   15   Male      140   Striker   2.94
('Tyeosri53', 24, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
44            44  Tyeosri53   24   Male        9
261          261  Tyeosri53   24   Male      141

                             Item Name  Price
44   Thorn, Conqueror of the Corrupted   2.73
261                         Persuasion   3.19
('Tyeudariasuir90', 21, 'Male')
     Purchase ID               SN  Age Gender  Item ID  \
216          216  Tyeudariasuir90   21   Male      136

                        Item Name  Price
216  Ghastly Adamantite Protector   3.58
('Tyeuduen32', 23, 'Male')
     Purchase ID          SN  Age Gender  Item ID            Item Name  Price
496          496  Tyeuduen32   23   Male       79  Alpha, Oath of Zeal   4.05
('Tyeurith29', 8, 'Male')
     Purchase ID          SN  Age Gender  Item ID  Item Name  Price
187          187  Tyeurith29    8   Male       11  Brimstone   3.65
('Tyialisti80', 23, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
736          736  Tyialisti80   23   Male       58

                             Item Name  Price
736  Freak's Bite, Favor of Holy Might   4.14
('Tyialisudeu65', 24, 'Male')
     Purchase ID             SN  Age Gender  Item ID  \
469          469  Tyialisudeu65   24   Male      148
654          654  Tyialisudeu65   24   Male       19

                              Item Name  Price
469  Warmonger, Gift of Suffering's End   4.03
654       Pursuit, Cudgel of Necromancy   1.02
('Tyida79', 24, 'Male')
     Purchase ID       SN  Age Gender  Item ID  \
29            29  Tyida79   24   Male       37
580          580  Tyida79   24   Male      178

                                        Item Name  Price
29            Shadow Strike, Glory of Ending Hope   3.16
580  Oathbreaker, Last Hope of the Breaking Storm   4.23
('Tyidaim51', 16, 'Female')
     Purchase ID         SN  Age  Gender  Item ID  \
267          267  Tyidaim51   16  Female       41
276          276  Tyidaim51   16  Female        9
714          714  Tyidaim51   16  Female      103

                             Item Name  Price
267                              Orbit   4.75
276  Thorn, Conqueror of the Corrupted   2.73
714                     Singed Scalpel   4.35
('Tyidainu31', 18, 'Female')
     Purchase ID          SN  Age  Gender  Item ID     Item Name  Price
317          317  Tyidainu31   18  Female        3  Phantomlight   2.49
('Tyirinu79', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID                  Item Name  \
172          172  Tyirinu79   21   Male       65  Conqueror Adamantite Mace

     Price
172   4.24
('Tyisur83', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID                  Item Name  \
58            58  Tyisur83   23   Male      152                  Darkheart
315          315  Tyisur83   23   Male      107  Splitter, Foe Of Subtlety
323          323  Tyisur83   23   Male      131                       Fury

     Price
58    1.74
315   2.18
323   1.44
('Umolrian85', 32, 'Female')
     Purchase ID          SN  Age  Gender  Item ID  \
85            85  Umolrian85   32  Female       33
210          210  Umolrian85   32  Female      136
436          436  Umolrian85   32  Female       80

                        Item Name  Price
85                     Curved Axe   1.16
210  Ghastly Adamantite Protector   3.58
436                     Dreamsong   3.39
('Undare39', 23, 'Male')
     Purchase ID        SN  Age Gender  Item ID     Item Name  Price
466          466  Undare39   23   Male      112  Worldbreaker   2.60
574          574  Undare39   23   Male      131          Fury   1.44
('Undassa89', 25, 'Male')
     Purchase ID         SN  Age Gender  Item ID Item Name  Price
332          332  Undassa89   25   Male      161    Devine   1.76
('Undilsan50', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID    Item Name  Price
241          241  Undilsan50   22   Male       10  Sleepwalker   1.79
('Undimsya85', 33, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
335          335  Undimsya85   33   Male       67

                                 Item Name  Price
335  Celeste, Incarnation of the Corrupted   3.46
('Undirra73', 34, 'Male')
     Purchase ID         SN  Age Gender  Item ID                    Item Name  \
308          308  Undirra73   34   Male       98  Deadline, Voice Of Subtlety

     Price
308   2.89
('Undirrala66', 22, 'Male')
     Purchase ID           SN  Age Gender  Item ID        Item Name  Price
114          114  Undirrala66   22   Male      150        Deathraze   2.85
223          223  Undirrala66   22   Male      142  Righteous Might   2.62
('Undirrasta89', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID               Item Name  \
462          462  Undirrasta89   20   Male      144  Blood Infused Guardian

     Price
462   1.94
('Undista85', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID             Item Name  Price
354          354  Undista85   21   Male      163  Thunderfury Scimitar   3.45
('Undjask33', 22, 'Male')
   Purchase ID         SN  Age Gender  Item ID  Item Name  Price
8            8  Undjask33   22   Male       21  Souleater    1.1
('Undjaskla97', 33, 'Male')
     Purchase ID           SN  Age Gender  Item ID  \
321          321  Undjaskla97   33   Male      118
689          689  Undjaskla97   33   Male       76

                            Item Name  Price
321  Ghost Reaver, Longsword of Magic   2.17
689          Haunted Bronzed Bludgeon   3.15
('Undosia27', 17, 'Male')
     Purchase ID         SN  Age Gender  Item ID      Item Name  Price
229          229  Undosia27   17   Male       72  Winter's Bite   3.77
('Undosian34', 21, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
90            90  Undosian34   21   Male       60
620          620  Undosian34   21   Male      109

                            Item Name  Price
90                               Wolf   3.54
620  Downfall, Scalpel Of The Emperor   4.76
('Undotesta33', 18, 'Male')
     Purchase ID           SN  Age Gender  Item ID              Item Name  \
704          704  Undotesta33   18   Male       95  Singed Onyx Warscythe

     Price
704   4.74
('Wailin72', 21, 'Female')
     Purchase ID        SN  Age  Gender  Item ID  \
283          283  Wailin72   21  Female        9

                             Item Name  Price
283  Thorn, Conqueror of the Corrupted   2.73
('Yadacal26', 15, 'Male')
     Purchase ID         SN  Age Gender  Item ID  \
337          337  Yadacal26   15   Male       17
497          497  Yadacal26   15   Male       52

                        Item Name  Price
337  Lazarus, Terror of the Earth   1.70
497                        Hatred   4.84
('Yadaisuir65', 20, 'Male')
     Purchase ID           SN  Age Gender  Item ID         Item Name  Price
625          625  Yadaisuir65   20   Male      133  Faith's Scimitar   4.09
('Yadam35', 28, 'Male')
     Purchase ID       SN  Age Gender  Item ID Item Name  Price
553          553  Yadam35   28   Male        2   Verdict   2.48
('Yadanu52', 34, 'Male')
    Purchase ID        SN  Age Gender  Item ID              Item Name  Price
60           60  Yadanu52   34   Male       44  Bonecarvin Battle Axe   2.38
('Yadaphos40', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
62            62  Yadaphos40   30   Male      178
421          421  Yadaphos40   30   Male       26

                                        Item Name  Price
62   Oathbreaker, Last Hope of the Breaking Storm   4.23
421                                   Unholy Wand   1.12
('Yalae81', 22, 'Male')
     Purchase ID       SN  Age Gender  Item ID  Item Name  Price
5              5  Yalae81   22   Male       81  Dreamkiss   3.61
447          447  Yalae81   22   Male      120     Agatha   3.08
('Yalaeria91', 33, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
681          681  Yalaeria91   33   Male       28

                            Item Name  Price
681  Flux, Destroyer of Due Diligence   1.06
('Yaliru88', 19, 'Male')

    Purchase ID        SN  Age Gender  Item ID                     Item Name  \
59           59  Yaliru88   19   Male      105  Hailstorm Shadowsteel Scythe

    Price
59   3.03
('Yalo85', 34, 'Male')
     Purchase ID      SN  Age Gender  Item ID  Item Name  Price
383          383  Yalo85   34   Male       11  Brimstone   3.65
('Yalostiphos68', 29, 'Male')
     Purchase ID             SN  Age Gender  Item ID   Item Name  Price
518          518  Yalostiphos68   29   Male      160  Azurewrath    4.4
('Yana46', 20, 'Female')
     Purchase ID      SN  Age  Gender  Item ID        Item Name  Price
280          280  Yana46   20  Female       16  Restored Bauble   3.55
('Yarithllodeu72', 22, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
364          364  Yarithllodeu72   22   Male       88

                            Item Name  Price
364  Emberling, Defender of Delusions   3.75
('Yarithrgue83', 20, 'Male')
     Purchase ID            SN  Age Gender  Item ID             Item Name  \
279          279  Yarithrgue83   20   Male      163  Thunderfury Scimitar

     Price
279   3.45
('Yarithrin84', 30, 'Female')
     Purchase ID           SN  Age  Gender  Item ID  \
698          698  Yarithrin84   30  Female       58

                             Item Name  Price
698  Freak's Bite, Favor of Holy Might   4.14
('Yarithsurgue62', 26, 'Male')
     Purchase ID              SN  Age Gender  Item ID  \
231          231  Yarithsurgue62   26   Male      139

                   Item Name  Price
231  Mercy, Katana of Dismay   4.94
('Yarolwen77', 30, 'Male')
     Purchase ID          SN  Age Gender  Item ID                 Item Name  \
696          696  Yarolwen77   30   Male       87  Deluge, Edge of the West

     Price
696   4.43
('Yasrisu92', 27, 'Male')
    Purchase ID         SN  Age Gender  Item ID Item Name  Price
46           46  Yasrisu92   27   Male      102   Avenger   3.44
('Yastyriaphos75', 22, 'Male')
     Purchase ID              SN  Age Gender  Item ID Item Name  Price
340          340  Yastyriaphos75   22   Male       41     Orbit   4.75
('Yasur35', 26, 'Male')
     Purchase ID       SN  Age Gender  Item ID                   Item Name  \
257          257  Yasur35   26   Male      175  Woeful Adamantite Claymore

     Price
257   4.48
('Yasur85', 21, 'Male')
     Purchase ID       SN  Age Gender  Item ID  Item Name  Price
514          514  Yasur85   21   Male       21  Souleater    1.1
('Yathecal72', 20, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
777          777  Yathecal72   20   Male       67

                                 Item Name  Price
777  Celeste, Incarnation of the Corrupted   3.46
('Yathecal82', 20, 'Female')
     Purchase ID          SN  Age  Gender  Item ID                Item Name  \
125          125  Yathecal82   20  Female       62              Piece Maker
548          548  Yathecal82   20  Female       75  Brutality Ivory Warmace
727          727  Yathecal82   20  Female      104       Gladiator's Glaive

     Price
125   1.87
548   2.42
727   1.93
('Yathedeu43', 22, 'Male')
     Purchase ID          SN  Age Gender  Item ID  \
93            93  Yathedeu43   22   Male       88
595          595  Yathedeu43   22   Male       55

                            Item Name  Price
93   Emberling, Defender of Delusions   3.75
595             Vindictive Glass Edge   2.27
('Yoishirrala98', 17, 'Female')
     Purchase ID             SN  Age  Gender  Item ID             Item Name  \
572          572  Yoishirrala98   17  Female      145  Fiery Glass Crusader

     Price
572   4.58
('Zhisrisu83', 10, 'Male')
     Purchase ID          SN  Age Gender  Item ID  Item Name  Price
54            54  Zhisrisu83   10   Male       25  Hero Cane   4.35
141          141  Zhisrisu83   10   Male       60       Wolf   3.54
('Zontibe81', 21, 'Male')
     Purchase ID         SN  Age Gender  Item ID   Item Name  Price
17            17  Zontibe81   21   Male      161      Devine   1.76
442          442  Zontibe81   21   Male       84  Arcane Gem   3.79
560          560  Zontibe81   21   Male        2     Verdict   2.48

In [40]:
# Find the total number of players
#First find the unique SN, then sum
unique_players= purchase_data['SN'].nunique()

pd.DataFrame({"Total Players": [unique_players]})

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.

* Create a summary data frame to hold the results

* Optional: give the displayed data cleaner formatting

* Display the summary data frame

In [41]:
#find the number of unique items
unique_items= purchase_data['Item Name'].nunique()

pd.DataFrame({"Unique Items": [unique_items]})

   Unique Items
0           179

In [42]:
#find the average price per item
average_price= purchase_data['Price'].mean()
average_price.round(2)
pd.DataFrame({"Average Price": [average_price.round(2)]})

   Average Price
0           3.05

In [43]:
# total number of purchases
total_purchases= purchase_data['Purchase ID'].count()
total_purchases
pd.DataFrame({"Total Purchases": [total_purchases]})

   Total Purchases
0              780

In [44]:
# find total revenue and round to 2 decimal places
total_revenue= purchase_data['Price'].sum()
total_revenue.round(2)
pd.DataFrame({"Total Revenue": [total_revenue.round(2)]})

   Total Revenue
0        2379.77

In [45]:
#Build summary data frame
summary_values= [{'Unique Items': unique_items, 'Average Price': average_price, 
                                    'Total Purchases': total_purchases, 'Total Revenue': total_revenue}]
summary_df= pd.DataFrame(summary_values)
summary_df['Average Price']=summary_df['Average Price'].map("${:,.2f}".format)
summary_df['Total Revenue']=summary_df['Total Revenue'].map("${:,.2f}".format)
summary_df
#How can I create a DataFrame based on the formulas so that it updates upon new value entry

   Unique Items Average Price  Total Purchases Total Revenue
0           179         $3.05              780     $2,379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [14]:
#IDEAS ON HOW TO GET UNIQUE GENDER COUNTS
#------------------------------------------

#count male, female, other
#I know i need to loop throught column['Gender']
#for gender_breakdown= purchas_data
 #   if ['Gender']= 'Male':
  #      male_count= male_count + 1
        
   # else ['Gender']= 'Female':
    #    female_count= female_count + 1
    
    #elif ['Gender']= 'Other/Non-Disclosed':
     #   other_count= other_count + 1
#print(male_count)
#print(female_count)
#print(other_count)

#gender_breakdown= purchase_data.groupby(['Gender'])

In [46]:
# count by gender
purchase_data_gender=purchase_data.loc[:, ['Gender', 'SN', 'Age']]
purchase_data_gender=purchase_data_gender.drop_duplicates()
#purchase_data_df

purchase_data_gender['Gender'].value_counts()

Male                     484
Female                    81
Other / Non-Disclosed     11
Name: Gender, dtype: int64

In [47]:
#percent by gender another option
#purchase_data_gender['Gender'].value_counts(normalize=True).map("{:,.2%}".format)

gender_count= purchase_data_gender['Gender'].value_counts()
gender_percent=gender_count/unique_players 
gender_analysis_df= pd.DataFrame({'Count': gender_count, 'Percentage': gender_percent})
gender_analysis_df['Percentage']=gender_analysis_df['Percentage'].map("{:,.2%}".format)
gender_analysis_df

                       Count Percentage
Male                     484     84.03%
Female                    81     14.06%
Other / Non-Disclosed     11      1.91%


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [48]:
groupby_purchase_data=purchase_data.groupby(['Gender'])
gender_counts=groupby_purchase_data.count()['Price']
gender_avg=groupby_purchase_data.mean()['Price']
gender_total=groupby_purchase_data.sum()['Price']
per_person=gender_total/gender_count
#took gender_count from gender analysis unique count

purchase_analysis_df=pd.DataFrame({"Purchase Count": gender_counts, "Average Purchase Price": gender_avg,
                                   "Total Purchase Value": gender_total, "Avg Total Purchase per Person": per_person})
purchase_analysis_df

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Gender,,,,
Female,113,3.203009,361.94,4.468395
Male,652,3.017853,1967.64,4.065372
Other / Non-Disclosed,15,3.346000,50.19,4.562727

In [49]:
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
...,...,...,...,...,...,...,...
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [50]:
purchase_data.describe()

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   92.114103    3.050987
std     225.310896    6.659444   52.775943    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   48.000000    1.980000
50%     389.500000   22.000000   93.000000    3.150000
75%     584.250000   25.000000  139.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

In [51]:
#find the max age to set last bin
print(purchase_data['Age'].max())

45

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [52]:
#Create bins
bins = [0, 9.90, 14.90, 19.90, 24.90, 29.90, 34.90, 39.90, 100]

# Create labels for these bins
age_demographics_labels = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34",
                "35-39", "40+"]

In [53]:
# Slice the data and place it into bins
pd.cut(purchase_data['Age'], bins, labels=age_demographics_labels)

0      20-24
1        40+
2      20-24
3      20-24
4      20-24
       ...
775    20-24
776    20-24
777    20-24
778      <10
779    20-24
Name: Age, Length: 780, dtype: category
Categories (8, object): [<10 < 10-14 < 15-19 < 20-24 < 25-29 < 30-34 < 35-39 < 40+]

In [54]:
#put age ranges in dataframe to run % and count calculations

purchase_data["Age Range"] = pd.cut(purchase_data["Age"], bins, labels= age_demographics_labels, include_lowest=True)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Range
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24

In [55]:
# Create a GroupBy object based upon "Age Range"
age_group = purchase_data.groupby("Age Range")

# Find how many rows fall into each bin-count by age
count_by_age= age_group["SN"].nunique()
count_by_age

Age Range
<10       17
10-14     22
15-19    107
20-24    258
25-29     77
30-34     52
35-39     31
40+       12
Name: SN, dtype: int64

In [56]:
#percent by age
percent_by_age= (count_by_age/unique_players)
percent_by_age.map("{:,.2%}".format)

Age Range
<10       2.95%
10-14     3.82%
15-19    18.58%
20-24    44.79%
25-29    13.37%
30-34     9.03%
35-39     5.38%
40+       2.08%
Name: SN, dtype: object

In [57]:
#DataFrame for count & percent by age
age_demographics = pd.DataFrame({"Total Count": count_by_age, "Percentage of Players": percent_by_age,})

# Format the data frame with no index name in the corner
age_demographics.index.name = None

# Format percentage with two decimal places 
age_demographics.style.format({"Percentage of Players":"{:,.2%}"})

In [58]:
#purchase data by age
purchase_count_by_age= age_group['Purchase ID'].count()
purchase_count_by_age

<10       23
10-14     28
15-19    136
20-24    365
25-29    101
30-34     73
35-39     41
40+       13
Name: Purchase ID, dtype: int64

In [59]:
#purchase price by age
avg_purch_price_by_age= age_group['Price'].mean()
avg_purch_price_by_age

<10      3.353478
10-14    2.956429
15-19    3.035956
20-24    3.052219
25-29    2.900990
30-34    2.931507
35-39    3.601707
40+      2.941538
Name: Price, dtype: float64

In [60]:
#Total purchase value
purchase_total_per_person= age_group['Price'].sum()
purchase_total_per_person

<10        77.13
10-14      82.78
15-19     412.89
20-24    1114.06
25-29     293.00
30-34     214.00
35-39     147.67
40+        38.24
Name: Price, dtype: float64

In [61]:
#Avg total purchase price by person
avg_totalpurchase_per_person= (purchase_total_per_person/count_by_age)
avg_totalpurchase_per_person

<10      4.537059
10-14    3.762727
15-19    3.858785
20-24    4.318062
25-29    3.805195
30-34    4.115385
35-39    4.763548
40+      3.186667
dtype: float64

In [62]:
#DataFrame for purchase analysis by age

#DataFrame for count & percent by age
#age_demographics = pd.DataFrame({"Total Count": count_by_age, "Percentage of Players": percent_by_age,})

# Format the data frame with no index name in the corner
#age_demographics.index.name = None

# Format percentage with two decimal places 
#age_demographics.style.format({"Percentage of Players":"{:,.2%}"})

purchase_analysis_age_df=pd.DataFrame({'Purchase Count': purchase_count_by_age ,
                                    'Average Purchase Price': avg_purch_price_by_age,
                                    'Total Purchase Value': purchase_total_per_person,
                                    'Avg Total Purchase per Person': avg_totalpurchase_per_person})
purchase_analysis_age_df['Average Purchase Price']= purchase_analysis_age_df['Average Purchase Price'].map("${:,.2f}".format)
purchase_analysis_age_df['Total Purchase Value']= purchase_analysis_age_df['Total Purchase Value'].map("${:,.2f}".format)
purchase_analysis_age_df['Avg Total Purchase per Person']=purchase_analysis_age_df['Avg Total Purchase per Person'].map("${:,.2f}".format)
purchase_analysis_age_df.index.name= None
purchase_analysis_age_df

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
<10,23,$3.35,$77.13,$4.54
10-14,28,$2.96,$82.78,$3.76
15-19,136,$3.04,$412.89,$3.86
20-24,365,$3.05,"$1,114.06",$4.32
25-29,101,$2.90,$293.00,$3.81
30-34,73,$2.93,$214.00,$4.12
35-39,41,$3.60,$147.67,$4.76
40+,13,$2.94,$38.24,$3.19

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [78]:
#Individual purchase data
players_purchase_count_df = purchase_data.groupby("SN").count()["Price"].rename("Purchase Count")
players_average_price_df = purchase_data.groupby("SN").mean()["Price"].rename("Average Purchase Price")
players_total_df = purchase_data.groupby("SN").sum()["Price"].rename("Total Purchase Value")

individual_purchase_data_df = pd.DataFrame({"Purchase Count":players_purchase_count_df,
                                   "Average Purchase Price": players_average_price_df,
                                   "Total Purchase Value": players_total_df})
individual_purchase_data_df.head(5)

              Purchase Count  Average Purchase Price  Total Purchase Value
SN
Adairialis76               1                    2.28                  2.28
Adastirin33                1                    4.48                  4.48
Aeda94                     1                    4.91                  4.91
Aela59                     1                    4.32                  4.32
Aelaria33                  1                    1.79                  1.79

In [91]:
#top 5 spenders sort
top_five_spenders_df = individual_purchase_data_df.sort_values("Total Purchase Value", ascending=False)
top_five_spenders_df['Average Purchase Price']= top_five_spenders_df['Average Purchase Price'].map("${:,.2f}".format)
top_five_spenders_df['Total Purchase Value']= top_five_spenders_df['Total Purchase Value'].map("${:,.2f}".format)
top_five_spenders_df.head()

             Purchase Count Average Purchase Price Total Purchase Value
SN
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [98]:
#Item purchase data
item_data=purchase_data.groupby(["Item ID", "Item Name"])
item_purchase_count_df = item_data['Item ID'].count()
item_price_df = item_data['Price'].unique().str[0]
item_purchase_value_df = item_data['Price'].sum()

item_analysis_df = pd.DataFrame({"Purchase Count":item_purchase_count_df,
                                   "Item Price": item_price_df,
                                   "Total Purchase Value": item_purchase_value_df})
                                
item_analysis_df.head()

                            Purchase Count  Item Price  Total Purchase Value
Item ID Item Name
0       Splinter                         4        1.28                  5.12
1       Crucifer                         3        3.26                  9.78
2       Verdict                          6        2.48                 14.88
3       Phantomlight                     6        2.49                 14.94
4       Bloodlord's Fetish               5        1.70                  8.50

In [99]:
#Sort Item purchase data frame
item_analysis_df = item_analysis_df.sort_values("Purchase Count", ascending=False)
item_analysis_df['Item Price']= item_analysis_df['Item Price'].map("${:,.2f}".format)
item_analysis_df['Total Purchase Value']= item_analysis_df['Total Purchase Value'].map("${:,.2f}".format)
item_analysis_df.head()

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
145,Fiery Glass Crusader,9,$4.58,$41.22
108,"Extraction, Quickblade Of Trembling Hands",9,$3.53,$31.77
82,Nirvana,9,$4.90,$44.10
19,"Pursuit, Cudgel of Necromancy",8,$1.02,$8.16

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [109]:
#New DataFrame sorted by Total Purchase Value

item_analysis_df = item_analysis_df.sort_values('Total Purchase Value', ascending=False)
item_analysis_df.head()

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
63,Stormfury Mace,2,$4.99,$9.98
29,"Chaos, Ender of the End",5,$1.98,$9.90
173,Stormfury Longsword,2,$4.93,$9.86
1,Crucifer,3,$3.26,$9.78
38,"The Void, Vengeance of Dark Magic",4,$2.37,$9.48